### ISSUE TITLE
Ability to set and save a default playback speed

### ISSUE THREAD

**Issue by Latrolage** [TeamPiped/Piped#725] opened 2022-01-13 14:51 UTC

**Comment by FireMasterK** [comment] 2022-01-13 22:43
Buy changing it when playing a video retains it for other videos, so isn't this already implemented?

**Comment by FireMasterK** [comment] 2022-01-14 12:42
Could you let me know if https://rate-change-fixes.piped.pages.dev/ fixes the issue?

**Comment by Latrolage** [comment] 2022-01-14 14:21
After closing the browser window and coming back, it's set back to 1.0x speed again.

**Comment by sdfg2** [comment] 2022-01-21 19:00
The problem is nothing is 'saved' to the account other than the subscriptions.  Not even watched videos.

I like this idea, and I'd like to extend it to a per-channel setting - there are huge variations in how much some channels speed up the speech, I have to do this back and forth depending on what I'm watching.  But that would mean properly implementing user accounts.

**Comment by FireMasterK** [comment] 2022-10-17 00:26
Closing this with #1573.

**Closed by FireMasterK** 2022-10-17 00:26 UTC
Labels: P2
