### ISSUE TITLE
Error code 1002, unable to play (CORS failures as well)

### ISSUE THREAD

**Issue by samip5** [TeamPiped/Piped#3527] opened 2024-04-03 05:46 UTC
### Official Instance

- [x] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

It seems that very often, when I haven't used my private ish instance, ytproxy will complain about CORS not succeeding as well as shakira player throwing error 1002.

### To Reproduce

1. Open any URL after the instance has been running for multiple days
2. See that sometimes you get Shaka error 1002
3. Unable to play.

### Expected behavior

I expected it to start playing instead.

### Logs/Errors

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://proxy.piped.fi/videoplayback?c=WEB&clen=14062691&cpn=GAQIOtxa2VbgeMNn&dur=1643.921&ei=mesMZqWvBtjJ0u8P7qSBuAc&expire=1712144377&fexp=51141542&fvip=5&gir=yes&host=rr2---sn-5goeenez.googlevideo.com&id=o-AORogJhFOD-8IfxWjUKtKDhPD_6nsxU5lMHIHLsXeCwc&initcwndbps=435000&ip=129.151.212.221&itag=250&keepalive=yes&lmt=1710355563840442&lsig=ALClDIEwRAIgVuiqhvlXkvLIg3jOPxDY_xdLG0wl8v2J8ylO4qoWYAECIAb2_RKE34424e6DODPBjsKG8xL_ZZS3DG0R3ScKMf3A&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&mh=BE&mime=audio%2Fwebm&mm=31%2C29&mn=sn-5goeenez%2Csn-5go7ynl6&ms=au%2Crdu&mt=1712122639&mv=m&mvi=2&n=Kn-CLidLpV_ZrA&ns=OGMuVIPORFy2Zld-aunfeUUQ&pl=19&requiressl=yes&sefc=1&sig=AJfQdSswRAIgbjPmnMBCRCXTFgfF1a9YkGnOHRa8COcYSmtwpaJRBmcCIGvpSJYDL5u0Ecx04iQhnHfP36pebLR5DlH1vIPxaHc8&source=youtube&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cxtags%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&spc=UWF9f90lVUIHX3zXmJucj_tDT3L9yk-vsd1WaFbprt9Pzfs&svpuc=1&txp=4532434&ump=1&vprv=1&xpc=EgVo2aDSNQ%3D%3D&xtags=acont%3Ddubbed%3Alang%3Des-US&range=259-3060. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://proxy.piped.fi/videoplayback?c=WEB&clen=14062691&cpn=GAQIOtxa2VbgeMNn&dur=1643.921&ei=mesMZqWvBtjJ0u8P7qSBuAc&expire=1712144377&fexp=51141542&fvip=5&gir=yes&host=rr2---sn-5goeenez.googlevideo.com&id=o-AORogJhFOD-8IfxWjUKtKDhPD_6nsxU5lMHIHLsXeCwc&initcwndbps=435000&ip=129.151.212.221&itag=250&keepalive=yes&lmt=1710355563840442&lsig=ALClDIEwRAIgVuiqhvlXkvLIg3jOPxDY_xdLG0wl8v2J8ylO4qoWYAECIAb2_RKE34424e6DODPBjsKG8xL_ZZS3DG0R3ScKMf3A&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&mh=BE&mime=audio%2Fwebm&mm=31%2C29&mn=sn-5goeenez%2Csn-5go7ynl6&ms=au%2Crdu&mt=1712122639&mv=m&mvi=2&n=Kn-CLidLpV_ZrA&ns=OGMuVIPORFy2Zld-aunfeUUQ&pl=19&requiressl=yes&sefc=1&sig=AJfQdSswRAIgbjPmnMBCRCXTFgfF1a9YkGnOHRa8COcYSmtwpaJRBmcCIGvpSJYDL5u0Ecx04iQhnHfP36pebLR5DlH1vIPxaHc8&source=youtube&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cxtags%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&spc=UWF9f90lVUIHX3zXmJucj_tDT3L9yk-vsd1WaFbprt9Pzfs&svpuc=1&txp=4532434&ump=1&vprv=1&xpc=EgVo2aDSNQ%3D%3D&xtags=acont%3Ddubbed%3Alang%3Des-US&range=0-258. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://proxy.piped.fi/videoplayback?c=WEB&clen=14062691&cpn=GAQIOtxa2VbgeMNn&dur=1643.921&ei=mesMZqWvBtjJ0u8P7qSBuAc&expire=1712144377&fexp=51141542&fvip=5&gir=yes&host=rr2---sn-5goeenez.googlevideo.com&id=o-AORogJhFOD-8IfxWjUKtKDhPD_6nsxU5lMHIHLsXeCwc&initcwndbps=435000&ip=129.151.212.221&itag=250&keepalive=yes&lmt=1710355563840442&lsig=ALClDIEwRAIgVuiqhvlXkvLIg3jOPxDY_xdLG0wl8v2J8ylO4qoWYAECIAb2_RKE34424e6DODPBjsKG8xL_ZZS3DG0R3ScKMf3A&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&mh=BE&mime=audio%2Fwebm&mm=31%2C29&mn=sn-5goeenez%2Csn-5go7ynl6&ms=au%2Crdu&mt=1712122639&mv=m&mvi=2&n=Kn-CLidLpV_ZrA&ns=OGMuVIPORFy2Zld-aunfeUUQ&pl=19&requiressl=yes&sefc=1&sig=AJfQdSswRAIgbjPmnMBCRCXTFgfF1a9YkGnOHRa8COcYSmtwpaJRBmcCIGvpSJYDL5u0Ecx04iQhnHfP36pebLR5DlH1vIPxaHc8&source=youtube&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cxtags%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&spc=UWF9f90lVUIHX3zXmJucj_tDT3L9yk-vsd1WaFbprt9Pzfs&svpuc=1&txp=4532434&ump=1&vprv=1&xpc=EgVo2aDSNQ%3D%3D&xtags=acont%3Ddubbed%3Alang%3Des-US&range=259-3060. (Reason: CORS request did not succeed). Status code: (null).

Object { severity: 2, category: 1, code: 1002, data: (3) […], handled: false, message: "Shaka Error 1002", stack: "I@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:3442\nu2/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:254450\nlo@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:3742\ncE/this.throw@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4135\nn@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4300\npromise callback*o@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4399\nhE/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4420\nhE@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4316\nC@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4454\nu2@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:253678\nda@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:253266\nof/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:58699\nJE@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:55528\nje.prototype.Fa/n/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:55308\npromise callback*je.prototype.Fa@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:55446\nof@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:58646\nof/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:59526\nJE@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:55528\nje.prototype.Fa/n/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:55308\npromise callback*je.prototype.Fa@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:55446\nof@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:59032\nd.request/s<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:57487\nJE@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:55528\nje.prototype.Fa/n/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:55308\npromise callback*je.prototype.Fa@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:55446\nd.request@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:57466\ndh@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:197021\nc4/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:196861\nlo@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:3742\ncE/this.next@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4040\nhE/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4423\nhE@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4316\nC@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4454\nc4@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:196783\nv@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:189695\ncm/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:155480\nlo@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:3742\ncE/this.next@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4040\nhE/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4423\nhE@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4316\nC@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4454\ncm@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:155334\nKc@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:155236\ni4/k.createSegmentIndex/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:191694\nlo@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:3742\ncE/this.next@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4040\nhE/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4423\nhE@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4316\nC@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4454\ni4/k.createSegmentIndex@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:191630\nqA/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:35256\nlo@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:3742\ncE/this.next@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4040\nhE/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4423\n" }
​
category: 1
​
code: 1002
​
data: Array(3) [ "https://proxy.piped.fi/videoplayback?c=WEB&clen=14062691&cpn=GAQIOtxa2VbgeMNn&dur=1643.921&ei=mesMZqWvBtjJ0u8P7qSBuAc&expire=1712144377&fexp=51141542&fvip=5&gir=yes&host=rr2---sn-5goeenez.googlevideo.com&id=o-AORogJhFOD-8IfxWjUKtKDhPD_6nsxU5lMHIHLsXeCwc&initcwndbps=435000&ip=129.151.212.221&itag=250&keepalive=yes&lmt=1710355563840442&lsig=ALClDIEwRAIgVuiqhvlXkvLIg3jOPxDY_xdLG0wl8v2J8ylO4qoWYAECIAb2_RKE34424e6DODPBjsKG8xL_ZZS3DG0R3ScKMf3A&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&mh=BE&mime=audio%2Fwebm&mm=31%2C29&mn=sn-5goeenez%2Csn-5go7ynl6&ms=au%2Crdu&mt=1712122639&mv=m&mvi=2&n=Kn-CLidLpV_ZrA&ns=OGMuVIPORFy2Zld-aunfeUUQ&pl=19&requiressl=yes&sefc=1&sig=AJfQdSswRAIgbjPmnMBCRCXTFgfF1a9YkGnOHRa8COcYSmtwpaJRBmcCIGvpSJYDL5u0Ecx04iQhnHfP36pebLR5DlH1vIPxaHc8&source=youtube&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cxtags%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&spc=UWF9f90lVUIHX3zXmJucj_tDT3L9yk-vsd1WaFbprt9Pzfs&svpuc=1&txp=4532434&ump=1&vprv=1&xpc=EgVo2aDSNQ%3D%3D&xtags=acont%3Ddubbed%3Alang%3Des-US&range=259-3060", TypeError, 1 ]
​
handled: false
​
message: "Shaka Error 1002"
​
severity: 2
​
stack: "I@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:3442\nu2/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:254450\nlo@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:3742\ncE/this.throw@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4135\nn@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4300\npromise callback*o@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4399\nhE/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4420\nhE@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4316\nC@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4454\nu2@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:253678\nda@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:253266\nof/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:58699\nJE@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:55528\nje.prototype.Fa/n/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:55308\npromise callback*je.prototype.Fa@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:55446\nof@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:58646\nof/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:59526\nJE@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:55528\nje.prototype.Fa/n/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:55308\npromise callback*je.prototype.Fa@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:55446\nof@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:59032\nd.request/s<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:57487\nJE@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:55528\nje.prototype.Fa/n/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:55308\npromise callback*je.prototype.Fa@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:55446\nd.request@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:10:57466\ndh@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:197021\nc4/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:196861\nlo@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:3742\ncE/this.next@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4040\nhE/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4423\nhE@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4316\nC@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4454\nc4@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:196783\nv@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:189695\ncm/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:155480\nlo@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:3742\ncE/this.next@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4040\nhE/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4423\nhE@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4316\nC@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4454\ncm@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:155334\nKc@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:155236\ni4/k.createSegmentIndex/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:191694\nlo@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:3742\ncE/this.next@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4040\nhE/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4423\nhE@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4316\nC@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4454\ni4/k.createSegmentIndex@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:191630\nqA/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:15:35256\nlo@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:3742\ncE/this.next@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4040\nhE/<@https://piped.fi/assets/shaka-player.ui-vTahH29n.js:6:4423\n"
​
<prototype>: Object { toString: toString()
, … }
[VideoPlayer.vue:623:28](https://piped.fi/src/components/VideoPlayer.vue)
    setPlayerAttrs VideoPlayer.vue:623
    (Async: promise callback)
    setPlayerAttrs VideoPlayer.vue:622
    loadVideo VideoPlayer.vue:347
    loadVideo VideoPlayer.vue:306
    mounted WatchVideo.vue:406
    (Async: promise callback)
    mounted WatchVideo.vue:379
    Vt runtime-core.esm-bundler.js:2865
    zt runtime-core.esm-bundler.js:195
    rt runtime-core.esm-bundler.js:202
    __weh runtime-core.esm-bundler.js:2845
    fc runtime-core.esm-bundler.js:370
    dc runtime-core.esm-bundler.js:408
    (Async: promise callback)
    uc runtime-core.esm-bundler.js:311
    _o runtime-core.esm-bundler.js:305
    effect runtime-core.esm-bundler.js:6129
    Us reactivity.esm-bundler.js:264
    Gl reactivity.esm-bundler.js:308
    Ur reactivity.esm-bundler.js:1075
    set value reactivity.esm-bundler.js:1120
    H vue-router.mjs:3361
    U vue-router.mjs:3226
    (Async: promise callback)
    U vue-router.mjs:3193
    y vue-router.mjs:3118
    install vue-router.mjs:3559
    use runtime-core.esm-bundler.js:3843
    <anonymous> main.js:617
```

### Browser, and OS with Version.

Firefox v124.0.1 Gentoo

**Comment by Bnyro** [comment] 2024-04-03 11:43
Duplicate of https://github.com/TeamPiped/Piped/issues/2915

**Closed by Bnyro** 2024-04-03 11:43 UTC
Labels: bug
