### ISSUE TITLE
Videos do not play on the official instances

### ISSUE THREAD

**Issue by distrair** [TeamPiped/Piped#2816] opened 2023-08-15 13:57 UTC
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Videos do not play on any of the official instances

### To Reproduce

Open a video on any of the official instance

### Expected behavior

Video plays

### Logs/Errors

This is the only thing I got:
`GET https://pipedproxy-ams-2.kavin.rocks/videoplayback?expire=1692128680&ei=SIHbZM3aIcWnx_APj9SqgAY&ip=144.21.40.247&id=o-AJPxmT2g1o1LkGf9da0ONBl-SL3y1FApbRtAcaZLKD7f&itag=251&source=youtube&requiressl=yes&mh=p1&mm=31%2C26&mn=sn-5hne6nsz%2Csn-2gb7sne6&ms=au%2Conr&mv=m&mvi=5&pl=23&initcwndbps=152500&spc=UWF9fx78setU-pPtqk_6Lo4lJVjySo0&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=414017&dur=27.841&lmt=1692105380184157&mt=1692106660&fvip=2&keepalive=yes&fexp=24007246%2C24363391&c=ANDROID&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgJoMvHgTlJ8A_uHHC-ElaHDLTQcS8EY8cAlhPxjGNhMECIH8K3imgv_0ka2ThG6dPcXs5TLRVefYeulHSkOZ4WzG5&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALY5ERanwgW3YwkxbXHTc-YqNvgUnQl1oM5xGK5pMUl1AiAlQFqNppEyghkCUhbnWGVwl3hLMFsYI2kcHqpPHGZtqg%3D%3D&cpn=ntF30Hl-lrhy7CuM&host=rr5---sn-5hne6nsz.googlevideo.com&range=0-265 403`
This shows up when you try to play video on Yattee:
`You do not have permission to access the requested resource.`

### Browser, and OS with Version.

Brave 1.56.20 on Windows 11

**Comment by Bnyro** [comment] 2023-08-15 14:05
Duplicate of #2809

**Closed by Bnyro** 2023-08-15 14:05 UTC
Labels: bug
