### ISSUE TITLE
Double tap to skip forward/backward

### ISSUE THREAD

**Issue by IoIxD** [TeamPiped/Piped#3027] opened 2023-10-15 08:08 UTC
### Describe the feature

The (maybe toggleable) ability to double tap the left side of the player to go 10 seconds backwards or the right side of the player to go 10 econds forwards.

### Why would this be useful to add?

I've actually come to rely on this when watching videos on mobile, either for skipping parts of a video or seeing something I missed.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-10-16 20:53
Duplicate of #127

**Closed by Bnyro** 2023-10-16 20:53 UTC
Labels: enhancement
