### ISSUE TITLE
YouTube IP banned?

### ISSUE THREAD

**Issue by r2fo** [TeamPiped/Piped#3060] opened 2023-10-24 17:54 UTC
### Describe your question

Today I noticed that my instance successfully loads titles and thumbnails, but video’s don’t play. After multiple docker and server restarts, I setup a VPN on my server and tried to open YouTube.com through my server’s IP address. To my surprise video playback did not work on YouTube as well. After changing the public IPv4 address of my VPS, video playback was working on both Piped and YouTube.

I did not expect them to block my IP address that quickly, I’ve heard of other instances getting banned but mine is just more than a week old. Would IPv6 counter this blockage?

Edit: it seems like my instance was getting throttled (possible bot abuse?). Here is my log file (I can’t attach anything since I’m on mobile):

Edit2: I assigned some IPv6 addresses to my server to bypass the IP blocking. Fortunately my provider gave me a /56 range.

```
Database is up to date, no changesets to execute

UPDATE SUMMARY
Run:                          0
Previously run:               3
Filtered out:                 0
-------------------------------
Total change sets:            3

ThrottlingCache: 0 entries
Logged in as user: null
Room ID: !REDACTED:matrix.org
Filter ID: null
Database connection is ready!
Cleanup: Removed 0 old videos
PubSub: queue size - 29173 channels
ThrottlingCache: 247 entries
Cleanup: Removed 153 old videos
PubSub: queue size - 24069 channels
ThrottlingCache: 300 entries
Cleanup: Removed 4 old videos
Failed to subscribe: 429
Throttled.
[...]
Failed to subscribe: 429
Throttled.
ThrottlingCache: 261 entries
Cleanup: Removed 3 old videos
PubSub: queue size - 9 channels
Failed to subscribe: 429
Throttled.
[...]
Failed to subscribe: 429
Throttled.
ThrottlingCache: 314 entries
Cleanup: Removed 63 old videos
PubSub: queue size - 5 channels
ThrottlingCache: 265 entries
Cleanup: Removed 27 old videos
ThrottlingCache: 204 entries
Cleanup: Removed 7 old videos
PubSub: queue size - 0 channels
ThrottlingCache: 316 entries
Cleanup: Removed 47 old videos
PubSub: queue size - 0 channels
ThrottlingCache: 266 entries
Cleanup: Removed 0 old videos
Failed to subscribe: 429
Throttled.
ThrottlingCache: 302 entries
Cleanup: Removed 1 old videos
PubSub: queue size - 2 channels
ThrottlingCache: 227 entries
Cleanup: Removed 0 old videos
PubSub: queue size - 0 channels
Failed to subscribe: 429
Throttled.
[...]
Failed to subscribe: 429
Throttled.
ThrottlingCache: 216 entries
Cleanup: Removed 74 old videos
ThrottlingCache: 223 entries
Cleanup: Removed 3 old videos
PubSub: queue size - 29 channels
Failed to subscribe: 429
Throttled.
[...]
Failed to subscribe: 429
Throttled.
ThrottlingCache: 200 entries
Cleanup: Removed 1 old videos
PubSub: queue size - 24 channels
ThrottlingCache: 126 entries
Cleanup: Removed 6 old videos
ThrottlingCache: 112 entries
Cleanup: Removed 115 old videos
PubSub: queue size - 0 channels
Failed to subscribe: 429
Throttled.
[...]
Failed to subscribe: 429
Throttled.
ThrottlingCache: 205 entries
Cleanup: Removed 27 old videos
Failed to subscribe: 429
Throttled.
[...]
Failed to subscribe: 429
Throttled.
PubSub: queue size - 84 channels
ThrottlingCache: 320 entries
Cleanup: Removed 73 old videos
ThrottlingCache: 277 entries
Cleanup: Removed 62 old videos
PubSub: queue size - 0 channels
Failed to subscribe: 429
Throttled.
[...]
Failed to subscribe: 429
Throttled.
ThrottlingCache: 302 entries
Cleanup: Removed 5 old videos
PubSub: queue size - 11 channels
Failed to subscribe: 429
Throttled.
[...]
Failed to subscribe: 429
Throttled.
ThrottlingCache: 420 entries
Cleanup: Removed 45 old videos
ThrottlingCache: 550 entries
Cleanup: Removed 21 old videos
PubSub: queue size - 23 channels
ThrottlingCache: 353 entries
Cleanup: Removed 100 old videos
PubSub: queue size - 0 channels
Failed to subscribe: 429
Throttled.
[...]
Failed to subscribe: 429
Throttled.
ThrottlingCache: 436 entries
Cleanup: Removed 53 old videos
ThrottlingCache: 574 entries
Cleanup: Removed 1035 old videos
PubSub: queue size - 12 channels
ThrottlingCache: 536 entries
Cleanup: Removed 264 old videos
PubSub: queue size - 17 channels
ThrottlingCache: 405 entries
Cleanup: Removed 171 old videos
Failed to subscribe: 429
Throttled.
[...]
Failed to subscribe: 429
Throttled.
ThrottlingCache: 256 entries
Cleanup: Removed 377 old videos
PubSub: queue size - 14 channels
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid7.hprof ...
Heap dump file created [1500481816 bytes in 20.455 secs]
ThrottlingCache: 237 entries
Cleanup: Removed 274 old videos
PubSub: queue size - 2 channels
ThrottlingCache: 6 entries
Cleanup: Removed 602 old videos
ThrottlingCache: 0 entries
Cleanup: Removed 410 old videos
PubSub: queue size - 2 channels
ThrottlingCache: 0 entries
Cleanup: Removed 31 old videos
PubSub: queue size - 2 channels
ThrottlingCache: 0 entries
Cleanup: Removed 12 old videos
ThrottlingCache: 0 entries
Cleanup: Removed 14 old videos
PubSub: queue size - 2 channels
ThrottlingCache: 0 entries
Cleanup: Removed 30 old videos
PubSub: queue size - 2 channels
ThrottlingCache: 0 entries
Cleanup: Removed 62 old videos
ThrottlingCache: 0 entries
Cleanup: Removed 2 old videos
PubSub: queue size - 2 channels
Database is up to date, no changesets to execute

UPDATE SUMMARY
Run:                          0
Previously run:               3
Filtered out:                 0
-------------------------------
Total change sets:            3

ThrottlingCache: 0 entries
Logged in as user: null
Room ID: !REDACTED:matrix.org
Filter ID: null
Database connection is ready!
Cleanup: Removed 0 old videos
PubSub: queue size - 2 channels
Database is up to date, no changesets to execute

UPDATE SUMMARY
Run:                          0
Previously run:               3
Filtered out:                 0
-------------------------------
Total change sets:            3

ThrottlingCache: 0 entries
Logged in as user: null
Room ID: !REDACTED:matrix.org
Filter ID: null
Database connection is ready!
Cleanup: Removed 0 old videos
PubSub: queue size - 0 channels
Database is up to date, no changesets to execute

UPDATE SUMMARY
Run:                          0
Previously run:               3
Filtered out:                 0
-------------------------------
Total change sets:            3

ThrottlingCache: 0 entries
Logged in as user: null
Room ID: !REDACTED:matrix.org
Filter ID: null
Database connection is ready!
Cleanup: Removed 2 old videos
PubSub: queue size - 0 channels
```

**Comment by drgns-wtd** [comment] 2023-10-24 22:12
This has also happened to the drgns.space instance last night (Oct 23, 2AM UTC), it may be a new IP ban wave

**Comment by Bnyro** [comment] 2023-10-30 17:30
Please consult one of our [public chat rooms](https://github.com/TeamPiped/Piped#public-chat-rooms) for help with hosting an instance or general questions concerning how Piped works. We're deprecating the question label in issues.

Also a duplicate of #2809

**Closed by Bnyro** 2023-10-30 17:30 UTC
Labels: question

**Comment by script26** [comment] 2025-01-17 00:30
Really hope to see a client side IP address implementation of this rather than server side IP address. I think that would solve YouTube banning instances issue, and makes server maintenance easier, but requires user to handle IP, which is easier to change with tor/VPN anyway
