### ISSUE TITLE
manually change playlist order

### ISSUE THREAD

**Issue by Plathix** [TeamPiped/Piped#3056] opened 2023-10-23 18:21 UTC
### Describe the feature

Ability to manually move videos in a playlist to change the order they are played. To be clear, _not_ sorting by date or title. This would be something you do manually for each video, moving it up or down in the watch order.

### Why would this be useful to add?

I have playlists that I like to watch in specific order, and I currently can't change the order after I've already added the video. The only way to do it is to add the videos in the order you want in the first place, which isn't a great solution when you have a large playlist.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-05-04 14:58
duplicate of #964

**Closed by Bnyro** 2024-05-04 14:58 UTC
Labels: enhancement, P4
