### ISSUE TITLE
Sort by date

### ISSUE THREAD

**Issue by probonopd** [TeamPiped/Piped#275] opened 2021-07-18 18:09 UTC
It would be nice if one could sort the search results by date.

**Comment by FireMasterK** [comment] 2021-07-18 18:25
We would require NewPipeExtractor to add support for this first.

**Comment by krafi99** [comment] 2022-10-22 05:19
@

> We would require NewPipeExtractor to add support for this first.

Can you take help from Invidious source code for this and other sorting features? Invidious has all of that!!

**Comment by FireMasterK** [comment] 2022-10-22 11:04
No, you would have to wait for https://github.com/TeamNewPipe/NewPipeExtractor/pull/904 to get merged first.

**Comment by Bnyro** [comment] 2024-03-15 13:57
duplicate of #1376

**Closed by Bnyro** 2024-03-15 13:57 UTC
Labels: P3, requires NPE changes
