### ISSUE TITLE
Updating subscription feeds

### ISSUE THREAD

**Issue by hugoamvieira** [TeamPiped/Piped#1666] opened 2022-11-02 19:22 UTC
### Describe your question

Hey there,

I didn't want to expose my instance to the world, or have a complicated setup to proxy PubSub call-backs. 

Early on with using Piped, I discovered that the channel pages were always kept fairly up-to-date, however the subscription feed page would not update at all unless I visited the channel page, so I wrote some software to do requests to Piped's Backend, on the `/channel/:channelId` endpoint (thereby simulating a channel page visit). I have this running as a loop, listing all the subscriptions from the database.

This worked perfectly until very recently. Now, seemingly with the introduction of channel tabs, it looks like this `/channel/:channelId` endpoint no longer returns shorts and livestreams, meaning that content doesn't appear on my feed anymore.

I tried changing my tool to also now use the `tabs` data that comes in the `/channel/:channelId` endpoint and make a request to `/channels/tabs` with that data, and while that does list out that missing content, it does not seem to update the feed page.

As far as I have figured out, for the feed to be updated now (at least with livestreams), I have to actually open the video, and then it'll be shown on the subscription feed in a really weird way - the uploaded timestamp is completely wrong, so it ends up being ordered incorrectly.

I understand this is likely not a supported use case, however it did work really well for months. I am wondering if there's some other way to keep my subscription feed page updated without using pubsub.

Thanks!

**Comment by FireMasterK** [comment] 2022-11-02 19:25
Duplicate of #707

I'll add support to add handle new videos from channel tabs.

**Closed by FireMasterK** 2022-11-02 19:25 UTC
Labels: question
