### ISSUE TITLE
[Feature Request] Sort subscriptions into categories

### ISSUE THREAD

**Issue by trymeouteh** [TeamPiped/Piped#793] opened 2022-02-08 03:54 UTC
Please add a feature to allow you to sort subscriptions into categories to allow you to have a feed for all of your subscriptions, a feed for your gaming subscriptions, a feed for your sports subscriptions, a feed for your music subscriptions, etc.

**Comment by FireMasterK** [comment] 2022-02-08 09:37
Duplicate of #490

**Closed by FireMasterK** 2022-02-08 09:37 UTC
