### ISSUE TITLE
Comments disappear on expanding replies

### ISSUE THREAD

**Issue by foxjaw** [TeamPiped/Piped#3484] opened 2024-03-19 11:37 UTC
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

The main comment disappears / vanishes once the replies of it, is expanded.

### To Reproduce

This is very random. Can only be reproduced when you expand replies of many comments continuously for sometime.

### Expected behavior

The reply section should be expanded instead of the main comment itself disappearing.

### Browser, and OS with Version.

On all platforms.

**Comment by barelyprofessional** [comment] 2024-03-26 15:50
I've been having this issue. It's difficult to debug as it's so temperamental. This is the best I have:
Browser Console Error:
`TypeError: can't access property "commentId", f is undefined`

HTTP Response from Piped:
`{"error":"org.schabi.newpipe.extractor.exceptions.ParsingException: Unable to get parse youtube comments\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.collectCommentsFrom(YoutubeCommentsExtractor.java:255)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.extractComments(YoutubeCommentsExtractor.java:206)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:199)\n\tat org.schabi.newpipe.extractor.comments.CommentsInfo.getMoreItems(CommentsInfo.java:79)\n\tat me.kavin.piped.server.handlers.StreamHandlers.commentsPageResponse(StreamHandlers.java:372)\n\tat me.kavin.piped.server.ServerLauncher.lambda$mainServlet$27(ServerLauncher.java:247)\n\tat io.activej.http.AsyncServlet.lambda$ofBlocking$0(AsyncServlet.java:43)\n\tat io.activej.promise.Promise.lambda$ofBlocking$12(Promise.java:249)\n\tat java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)\n\tat java.base/java.lang.VirtualThread.run(VirtualThread.java:309)\nCaused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Unable to get commentRenderer\n\tat org.schabi.newpipe.extractor.utils.JsonUtils.getValue(JsonUtils.java:37)\n\tat org.schabi.newpipe.extractor.utils.JsonUtils.getValues(JsonUtils.java:91)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.collectCommentsFrom(YoutubeCommentsExtractor.java:253)\n\t... 9 more\n","message":"Unable to get parse youtube comments"}`

Docker logs from piped-backend show basically the same as what's in the HTTP response. If there's anything that can be done to bump the logging level to garner more info then please someone advise as the documentation for self hosting doesn't have any guidance.

**Comment by manuelkamp** [comment] 2024-04-06 15:04
same here

**Comment by Bnyro** [comment] 2024-04-25 18:22
Has been fixed with a NewPipeExtractor update some weeks ago.

**Closed** 2024-04-25 18:22 UTC
Labels: bug
