### ISSUE TITLE
seekbar preview not disappearing.

### ISSUE THREAD

**Issue by NeeRaj-2401** [TeamPiped/Piped#2321] opened 2023-04-22 07:11 UTC
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

@Bnyro  the seekbar preview is not stable, sometimes it just don't disappears.

<img src="https://user-images.githubusercontent.com/88180887/233768887-cbf23083-7268-4bf7-a8ac-2a22a2a05a3b.png" width="50%">

### To Reproduce

i m not able to figure out specifically which steps led to reproduce this bug, but it exists :(

### Expected behavior

the preview should only be visible till mouse is hovered over the bar

### Logs/Errors

NA

**Comment by Bnyro** [comment] 2023-04-22 07:16
Duplicate of #2318

**Closed by Bnyro** 2023-04-22 07:16 UTC
Labels: bug
