### ISSUE TITLE
A small Bug with Feed not showing newly uploaded videos sometimes

### ISSUE THREAD

**Issue by XSpark0** [TeamPiped/Piped#3039] opened 2023-10-18 11:25 UTC
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Feed wont show newly uploaded videos from Channel until i visit the Subscribed Channel's page and then go back to Feed and refresh page. 

### To Reproduce

1. Open Feed. (You will notice newly uploaded video from Channel not showing up in Feed.)
2. Go to Subscribed Channel's Page. (You will see the newly uploaded video that got uploaded few minutes to few hours ago.)
3. Now go back to Feed and refresh page. (Now the video appears in Feed.)

### Expected behavior

New uploaded video should immediately show up in Feed without having to go to Subscribed Channel's page.

### Browser, and OS with Version.

Chrome 118. Windows 11 22H2.

**Comment by Bnyro** [comment] 2023-10-18 14:13
Duplicate of #1130

**Closed by Bnyro** 2023-10-18 14:13 UTC
Labels: bug
