### ISSUE TITLE
Playlist support?

### ISSUE THREAD

**Issue by 6Tsiox9** [TeamPiped/Piped#586] opened 2021-10-31 16:11 UTC
It says there are playlist support but I'm not able to make it play in a playlist, it only shows all the videos in the playlist but I cannot make it play all together, idk if I'm blind or if there are no such function yet? or do I have to make an account to be able to play the playlist?

And yes the playlist is public.
When I click a video in the playlist it will only play the video separately. 
I use browser only.

**Comment by FireMasterK** [comment] 2021-10-31 17:28
Duplicate of #188

**Closed by FireMasterK** 2021-10-31 17:28 UTC
