### ISSUE TITLE
some channels are missing in feed until you not open channel page

### ISSUE THREAD

**Issue by kotsmotritnastul** [TeamPiped/Piped#1634] opened 2022-10-28 21:35 UTC
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

some videos or entire channels are missing even when i subscribed to them

### To Reproduce

1. open feed page knowing that some channel published new video https://i.imgur.com/99iJ3lV.jpeg
2. this video (or videos) may be missing
3. open channel page https://i.imgur.com/pk3IBtG.jpeg
4. open feed page again and press ctrl+f5
5. now videos from this channel are not missing https://i.imgur.com/nepbEf2.jpeg

### Expected behavior

  every recent video from every channel i subscribed to is here

### Logs/Errors

i dont know what javascript console is, does it exist in my browser?

### Browser, and OS with Version.

Vivaldi | 5.5.2805.42 (Stable channel) stable (64 bit)
Fedora 36

### Additional context

note that this bug does not occur with all channels, maybe it occurs only with not popular channels.
and most important thing - this can happen not only to newest videos, its not like piped could not fetch video from youtube that been published a minute ago. videos that are 1-4 days old may be missing too.
    
i have reproduced this bug on official instance (before feed started to return 500 code) and on li.ax, i think it can be reproduced everywhere. maybe the reason is i didnt subscribe to channel in natural way, i just imported subscriptions.json to piped instance and who know, maybe piped instance doesnt fetch list of videos from every channel that has been mentioned in subscriptions.json - only from channels that been manually visited by users of this particular instance.

**Comment by helpthemfix** [comment] 2022-10-29 21:05
I reported this many times and it's still an issue. The solution is indeed opening the channel page then it shows in feed.

**Comment by Bnyro** [comment] 2022-11-01 09:09
dupe of #1130

**Closed by Bnyro** 2022-11-01 09:09 UTC
Labels: bug
