### ISSUE TITLE
Not obvious if a video is in a playlist.

### ISSUE THREAD

**Issue by Latrolage** [TeamPiped/Piped#1037] opened 2022-05-06 10:22 UTC
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

It's currently not obvious whether or not a video you are watching is part of a playlist without looking at the URL. There is also no way (that I could find?) of going back to the playlist list.

Videos from the same playlist seem to be placed in the same place as recommended videos would usually be placed but again, nothing differentiates this from how it looks with normal recommended videos.

e.g. if I was sent a video from a playlist and I couldn't tell that it was a playlist without looking at the URL.

### To Reproduce

_ _

### Expected behavior

Make it more obvious that the videos in the place of the recommended videos are part of the playlist. e.g. Youtube makes those videos part of a scrollable list above the normal recommended videos

Create a button to go to the playlist it is from.

### Logs/Errors

_ _

**Comment by EdwardLangdon** [comment] 2022-05-06 15:56
Duplicate of #968

**Closed** 2023-01-26 20:57 UTC
Labels: bug
