### ISSUE TITLE
Implement Stories & community posts by Creators

### ISSUE THREAD

**Issue by NR8124** [TeamPiped/Piped#1143] opened 2022-06-18 16:34 UTC
**Describe your suggested feature**
Youtube Creators uploads stories and community posts on their channel for better interaction with their subscribers. So it would be better if these things would be integrated with Piped also.

**Other details**
I love your work and appreciate it...❤🙌

**Comment by Bnyro** [comment] 2022-09-07 18:35
Dupe of #662

**Closed** 2022-09-07 18:35 UTC
Labels: requires NPE changes
