### ISSUE TITLE
Error Code 1002

### ISSUE THREAD

**Issue by Pamilg8** [TeamPiped/Piped#3438] opened 2024-03-04 17:22 UTC
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

You get this error sometimes while playing video on any server. Video cannot be buffered. Thumbnails appear when scrolling in the search bar

### To Reproduce

1. https://youtu.be/cgmhimjsczk&t=62
Or https://piped.video/watch?v=cgmhimjsczk&t=62
2. Piped proxy is open
3. Server uptime is excellent. Other videos open quickly
4. This problem existed before the YouTube blocking problem. It was happening when Piped was still in its infancy. So it's not about high traffic

### Expected behavior

Watch the video

### Logs/Errors

.
### Browser, and OS with Version.

Chrome 122.0.6261.90. This also happens in LibreTube

### Additional context

![Screenshot_20240304-210600_Chrome](https://github.com/TeamPiped/Piped/assets/149590337/65882d73-ef17-44a6-a6fc-03e862ef80e8)

**Comment by Cade66** [comment] 2024-03-04 22:30
https://piped.video/watch?v=cgmhimjsczk&t=62  runs fine here, though a little long to start.
https://piped.adminforge.de/watch?v=cgmhimjsczk&t=62 starts quasi immediately.

Piped.video, though the official instance, is far from being the most reliable.
Consider as well, whatever the instance, to choose from the instance's Preferences page, the instance's instance, that is the instance's proxy (that pref should be renamed, confusing for beginners).

Not many reliable Piped instances at this time. Farside monitors quite well flawless instances of many front-ends:
Farside without Cloudflare-hosted instances : https://farside.link/
Farside with Cloudflare hosted instances : https://cf.farside.link/

**Comment by Pamilg8** [comment] 2024-03-05 04:18
> https://piped.video/watch?v=cgmhimjsczk&t=62 runs fine here, though a little long to start. https://piped.adminforge.de/watch?v=cgmhimjsczk&t=62 starts quasi immediately.
> 
> Piped.video, though the official instance, is far from being the most reliable. Consider as well, whatever the instance, to choose from the instance's Preferences page, the instance's instance, that is the instance's proxy (that pref should be renamed, confusing for beginners).
> 
> Not many reliable Piped instances at this time. Farside monitors quite well flawless instances of many front-ends: Farside without Cloudflare-hosted instances : https://farside.link/ Farside with Cloudflare hosted instances : https://cf.farside.link/

Even if it is related to the server, this is a confusing issue. Sometimes it happens. kavin.rocks was the most popular server and works great. Usually, when the server is down, it says there is a problem with the server.

**Comment by Bnyro** [comment] 2024-03-05 14:13
Duplicate of https://github.com/TeamPiped/Piped/issues/2915

**Closed by Bnyro** 2024-03-05 14:13 UTC
Labels: bug
