### ISSUE TITLE
Sorting by Most Watched

### ISSUE THREAD

**Issue by NikunjKhangwal** [TeamPiped/Piped#2246] opened 2023-03-23 05:53 UTC
### Describe the feature

While sorting by "Type" is good but it would've been cool if we also had "most watched" and maybe even "upload date" sort options.

### Why would this be useful to add?

Most watched videos simply gives you more relevant results. For example if you want to look for study material and need to know the popular options. Similarly upload date sorting let you explore new content more easily.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-09-14 15:33
Duplicate of #1376

**Closed by Bnyro** 2023-09-14 15:33 UTC
Labels: enhancement
