### ISSUE TITLE
more than 2X playback speed

### ISSUE THREAD

**Issue by p0mad** [TeamPiped/Piped#3583] opened 2024-05-01 08:27 UTC
### Describe the feature

hi
i was wondering if it is possible to have 2.5X or so on speed of the video playback?

### Why would this be useful to add?

better for slow videos

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-05-01 16:30
duplicate of https://github.com/TeamPiped/Piped/issues/923

**Closed by Bnyro** 2024-05-01 16:30 UTC
Labels: enhancement

**Comment by Bnyro** [comment] 2024-05-16 16:26
You can now press `Shift` and `s` at the same time to open a dialog which allows setting a custom playback speed.
