### ISSUE TITLE
A button to disable Piped Proxy

### ISSUE THREAD

**Issue by baalajimaestro** [TeamPiped/Piped#2328] opened 2023-04-23 14:29 UTC
### Describe the feature

Piped Proxy is typically hosted on a server, and this IP could very well get blacklisted by google, effectively messing up viewing videos. A button to disable calling the piped proxy which would inturn fetch everything directly from google servers, would really help since these are all residential IPs, and wouldn't be blacklisted. This would be almost identical to running NewPipe, but on browser.

### Why would this be useful to add?

Incase the user isnt worried about privacy they can just turn it on, and have much less latency, since its backed by google's CDN, adding to this, there is never a worry about rate-limits, if its coming from a residential IP.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment] 2023-04-23 15:25
Duplicate of #990

Google does not impose any sort of rate limit, you only see rate limits on HLS manifests, which I'm not fully sure what it is caused by, it's an API call technically anyway.

It's also almost impossible to do this, as CORS prevents you from fetching content from Google's servers if you're not on YouTube's site.

The only reason why the issue linked above is still open is that it would technically be possible with the help of a browser extension. The proxy performs the necessary header additions/removal behind the scenes for you.

**Closed by FireMasterK** 2023-04-23 15:25 UTC
Labels: enhancement
