### ISSUE TITLE
[URGENT ! issue] This =  https://piped.kavin.rocks/https://piped.kavin.rocks/watch?v=pAgnJDJN4VA&feature=youtu.be&listen=1

### ISSUE THREAD

**Issue by SiddharthSharma16923** [TeamPiped/Piped#1204] opened 2022-07-13 17:02 UTC
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug/ To Reproduce

went to `https://piped.kavin.rocks/watch?v=pAgnJDJN4VA`  
click the audio/listen button  
taken to `https://piped.kavin.rocks/https://piped.kavin.rocks/watch?v=pAgnJDJN4VA&feature=youtu.be&listen=1`

### Browser, and OS with Version.

Microsoft Edge
Version 103.0.1264.49 (Official build) (64-bit)
Win 10 21h2 19044.1766
### Additional context

seems like an update was passed irresponsibly

**Comment by honey-roast-coconut** [comment] 2022-07-14 05:25
Duplicate of #1194

**Comment by honey-roast-coconut** [comment] 2022-07-14 05:27
Duplicate of #1194

**Closed** 2022-07-19 03:59 UTC
Labels: bug
