### ISSUE TITLE
Subscription number is -1 on some channels and piped does not display all videos

### ISSUE THREAD

**Issue by weaponmasterjax** [TeamPiped/Piped#3549] opened 2024-04-11 18:03 UTC
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

On certain channels, the subscription number is displayed as -1, imo that means a failure right? Plus channel portfolio doesn't load as well. Besides that, the listed videos are far incomplete, only showing recent 6 months.

### To Reproduce

1. Goto piped channel page https://piped.video/channel/UC5g0kkbZtBX6_rwRcDSqZBQ
2. Displays incomplete info.

### Expected behavior

The subscription numbers are displayed correctly, along with all published videos displayed.

### Browser, and OS with Version.

Google Chrome 123.0.6312.99 on Android 13

**Comment by Bnyro** [comment] 2024-04-25 18:19
Duplicate of https://github.com/TeamPiped/Piped/issues/1130 and https://github.com/TeamNewPipe/NewPipeExtractor/pull/1170

**Closed by Bnyro** 2024-04-25 18:19 UTC
Labels: bug
