### ISSUE TITLE
Settings Not Being Saved

### ISSUE THREAD

**Issue by moriel5** [TeamPiped/Piped#131] opened 2021-04-16 15:43 UTC
I usually prefer setting the sponsor segments of the videos I watch, since I do like them (I watch mainly LinusTechTips (and their other channels), Gamers Nexus, and Level1Techs), and occasionally make use of them, so I tried disabling SponsorBlock and the other settings, however my changes do not get saved, and upon leaving the page, they get reverted.

**Comment by FireMasterK** [comment] 2021-04-16 19:30
There are two possibilities for this:
- You have cookies/localstorage disabled
- Something is preventing the settings from being saved in a particular browser

Can you take a screenshot of the localstorage tab in devtools? Please also specify the browser you are using.

**Comment by moriel5** [comment] 2021-04-17 17:41
Will do so once I can turn on my desktop again (real life chores first).

**Comment by moriel5** [comment] 2021-04-18 12:32
Sorry it took so long.
Oddly enough, on Edge, the values remained the same no matter what, while on Firefox they changed in accordance to what I had disabled (though still not saved).

![Screenshot from 2021-04-18 02:43:55](https://user-images.githubusercontent.com/20175297/115145616-fba2c900-a041-11eb-8d58-e87c31c1dd00.png)
![Screenshot from 2021-04-18 02:44:43](https://user-images.githubusercontent.com/20175297/115145618-fcd3f600-a041-11eb-894a-ac65aefedf55.png)

**Comment by FireMasterK** [comment] 2021-04-18 14:24
So, if I'm correct this is only reproducible when you disable everything. right?

**Comment by moriel5** [comment] 2021-04-18 14:26
It happens regardless of what I do, not just disabling everything.

**Comment by FireMasterK** [comment] 2021-04-18 14:28
I'm sorry, but I'm still unable to reproduce this issue, could you try without any extensions?

**Comment by moriel5** [comment] 2021-04-18 14:57
No problem, as soon as I'll be on my desktop.

**Comment by moriel5** [comment] 2021-04-18 15:36
While testing performance in issue #132, I checked (extensions enabled) and it appears that it only happens when disabling all options.

This is my sister's laptop, so I'll be running a proper check once I'm on my desktop (where Edge is also installed).

**Comment by FireMasterK** [comment] 2021-04-18 18:19
> Edge displays the same behaviour, as in, the settings do get saved, however attempting to disable all sponsorblock options resets all options to their defaults.

I was able to replicate this issue, thanks for reporting!

I'll fix this later tomorrow

**Comment by FireMasterK** [comment] 2021-04-21 13:39
This issue should be fixed now, do let me know if it isn't!

**Closed** 2021-04-21 13:39 UTC

**Comment by moriel5** [comment] 2021-04-21 19:08
Thanks, I'll test it out when on my desktop.
