### ISSUE TITLE
Video progress preview.

### ISSUE THREAD

**Issue by Nizami20052022** [TeamPiped/Piped#1564] opened 2022-10-12 04:49 UTC
### Describe the feature

Progress by swiping left and right on the video progress bar.

### Why would this be useful to add?

View the desired position in the video by previewing it in the video progress bar.

### Concept(s)

https://user-images.githubusercontent.com/104249296/195252808-8e7774e8-7bb0-4add-9748-f8bd8bcea2e3.mp4

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-10-12 18:42
Dupe of an older issue

**Closed by Bnyro** 2022-10-12 18:42 UTC
Labels: enhancement
