### ISSUE TITLE
[Wiki] Add Frontend URL for the Piped Instances

### ISSUE THREAD

**Issue by bachig26** [TeamPiped/Piped#1120] opened 2022-06-10 12:43 UTC
This is to add the Frontend URL to the [Piped Instances list](https://github.com/TeamPiped/Piped/wiki/Instances) in the Wiki.

_ps. I use open source apps available here in GitHub to access Piped Instances, but they need both the API URL and Frontend URL. I know that I just need to remove few letters in the API URL to execute it as Frontend URL, but sometimes it's a hassle to do. If the Frontend URL is also entered in the Wiki, this will make just the copy/paste and easy to go._

**Comment by EdwardLangdon** [comment] 2022-06-10 13:25
It won't be happening. See : https://github.com/TeamPiped/Piped/issues/716

Duplicate of #716 

So, Close this issue.

**Closed** 2022-07-19 18:25 UTC
