### ISSUE TITLE
Broadcast to TV.

### ISSUE THREAD

**Issue by Fertanima** [TeamPiped/Piped#1378] opened 2022-09-04 13:47 UTC
### Describe the feature

Option to cast to a TV (e.g. Chromecast or FireTv Stick)

### Why would this be useful to add?

Broadcast video to TV.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-09-04 14:23
Dupe of #681

**Closed by Bnyro** 2022-09-04 14:23 UTC
Labels: enhancement
