### ISSUE TITLE
Videos won’t appear and load

### ISSUE THREAD

**Issue by AcousticBirthdayCake** [TeamPiped/Piped#1066] opened 2022-05-18 07:50 UTC
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

When searching, on trending page or on your feed, the videos won’t appear/load.

### To Reproduce

1. Open piped.kavin.rocks
2. Go to Trending or Feed

### Expected behavior

Videos to load/appear

### Logs/Errors

No logs

### Browser, and OS with Version.

Safari iOS 15.4.1 and Safari iOS 15.5

**Comment by helpthemfix** [comment] 2022-05-18 08:06
Same here. The problem is present with all instances.

**Comment by EdwardLangdon** [comment] 2022-05-18 13:52
AFAIK, It's fixed. Try now.

**Comment by IronMaltese** [comment] 2022-05-18 14:01
It doesn't seem to be fixed for me and I'm on the official instance, I'm on iOS and this problem only happens over wifi, while on cellular it works fine

**Comment by IronMaltese** [comment] 2022-05-18 14:05
![image](https://user-images.githubusercontent.com/89056889/169060866-c86a1ddc-f9c9-495b-ad34-39bdbff8b62b.png)

**Comment by EdwardLangdon** [comment] 2022-05-18 14:21
Probably. I think it's time to close the issue as it's fixed.

**Closed** 2022-05-18 21:30 UTC
Labels: bug
