### ISSUE TITLE
Subtitles Spacing Issues

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#754] opened 2022-01-22 15:05 UTC
When you see the pictures below in the first picture with Video player not in full screen mode, notice the Subtitle Text Scale. It has one line spacing marked in Blue ink.

![UI 1](https://user-images.githubusercontent.com/87981739/150643916-c5bd3add-0c15-43a9-851f-9488bd8a7d6c.png)

But when the video player is in full screen mode, it has two lines of spacing. Which so much spacious. I think this could be fixed out. By reducing the spacing there so it will be much more minimal and easier to look and will be stunning in the Design portfolio.

![UI 2](https://user-images.githubusercontent.com/87981739/150643921-e12988ff-8ef0-4cba-800f-1da2566e5879.png)

I noticed there has been rehaul in the look of the Piped site, but after updating the Subtitles act very weird. See the Picture below:

![UI 3](https://user-images.githubusercontent.com/87981739/150643929-da31c3be-df13-4ae9-a28e-d7d25907913f.png)

As you see in the picture it is out of the Player and makes the video not so good.

**Comment by Loki-L1130** [comment] 2022-02-04 03:36
Duplicate of #448

**Comment by Loki-L1130** [comment] 2022-02-07 14:42
The spacing issue is actually fixed but I think you decrease the Subtitle Text Scale when in Full screen mode because it is too larger than YouTube.

**Comment by Loki-L1130** [comment] 2022-02-07 14:44
If you see in the 3rd Pic, It is out of the frame. But now, When I checked it back. It is bigger dark Black areas surrounded by it. I think you should check the Kimi trailer video and the specific subtitle.

**Closed** 2022-08-10 13:24 UTC
Labels: blocked, P2
