### ISSUE TITLE
Piped.video - links dont generate video teasers in 3rd party apps

### ISSUE THREAD

**Issue by Dinth** [TeamPiped/Piped#3603] opened 2024-05-09 05:45 UTC
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Recently i am trying to promote Piped in my circles by sharing videos via piped links instead of direct youtube links. 
Unfortunately, when im sharing a piped.video link via a third party messaging app (i have tried Discord, Telegram, Signal), the apps fail to generate a video teasers (with video thumbnail, title and descriptions) as they do with direct youtube links.
![image](https://github.com/TeamPiped/Piped/assets/313674/0f100bb2-af02-4d94-aa9e-06d948694638)

### To Reproduce

1. Copy a link to a video on piped.video instance
2. Paste it on Discord
3. Wait a second for the teaser to be generated

### Expected behavior

Video links should have teasers generated from the linked video similarly as it happens with youtube and other video sharing websites

### Browser, and OS with Version.

Not browser related

**Comment by Bnyro** [comment] 2024-05-09 14:09
Duplicate of https://github.com/TeamPiped/Piped/issues/1362

**Closed by Bnyro** 2024-05-09 14:09 UTC
Labels: bug
