### ISSUE TITLE
Preferences are saves to account, not browser cache

### ISSUE THREAD

**Issue by trymeouteh** [TeamPiped/Piped#1818] opened 2022-11-25 21:06 UTC
### Describe the feature

To have the Piped preferences be saved to the account and will always be the same on all devices as long your logged into the same account

### Why would this be useful to add?

If you change a setting on one device. It will be set on all the other devices.

If you clear your browser history, your settings will not be reset.

### Concept(s)

Saving the preferences just like how the subscriptions are saved to an account.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment] 2022-11-25 21:11
Duplicate of #496

**Closed by FireMasterK** 2022-11-25 21:11 UTC
Labels: enhancement
