### ISSUE TITLE
Videos randomly enter infinite buffering at a random point during playback

### ISSUE THREAD

**Issue by RetroAbstract** [TeamPiped/Piped#1355] opened 2022-08-30 14:36 UTC
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Often when watching videos through Piped, they will randomly get stuck and enter infinite buffering. Pausing & playing when this happens doesn't fix this, moving slightly ahead of the point where the video entered the infinite buffering doesn't fix this either, only refreshing the page and manually going to the point the video got stuck does.

### To Reproduce

I don't know how to manually produce this bug, best chance of having this occur is to simply watch videos, longer duration videos have higher chances of this happening.

### Expected behavior

The video watched through Piped would buffer and play smoothly without needing to refresh the page if the video gets stuck during playback.

### Logs/Errors

N/A

### Browser, and OS with Version.

Firefox 104.0 on Windows 10 Pro

**Comment by FireMasterK** [comment] 2022-10-11 16:39
Closing due to being unable to reproduce this issue.

**Closed by FireMasterK** 2022-10-11 16:39 UTC
Labels: bug

**Comment by IkelAtomig** [comment] 2022-12-26 04:15
This could happen when you are watching a video, Internet connection goes down, It is loaded already and plays until loaded when connection is. It still buffers and don't continue playing. I would recommend you to try this.

**Comment by selurvedu** [comment] 2023-02-25 23:19
I'm having the exact same issue on Firefox and Ungoogled Chromium on all instances from Libredirect, so I don't think it's a browser-specific or an instant-specific issue. Sometimes I have to reload the page 3 or 4 times for a ten-minute video.

> This could happen when you are watching a video, Internet connection goes down, It is loaded already and plays until loaded when connection is. It still buffers and don't continue playing. I would recommend you to try this.

Indeed, this reproduces the issue. I tried using a hardware switch on my laptop to disable Wi-Fi, but disconnecting via software would work too.

My test results:

1. If you disconnect while the video is playing and then reconnect while the playback has not reached the end of the buffered part yet, it will continue to buffer and the video will play as usual.
2. If you disconnect while the video is playing and the playback reaches the end of the buffered part while the device is still disconnected, the throbber will spin indefinitely and nothing but reloading the page will help.

With that said, I must point out that the problem I mentioned at the beginning of my comment may be caused by a similar, but separate bug, since buffering stops at random times while my laptop remains constantly connected to the internet. Or maybe not, and the same bug occurs because, say, the connection to the server closes prematurely for some reason, and Piped is unable to reconnect as described above.

@FireMasterK, please reopen.

**Comment by FireMasterK** [comment] 2023-02-26 00:13
> With that said, I must point out that the problem I mentioned at the beginning of my comment may be caused by a similar, but separate bug, since buffering stops at random times while my laptop remains constantly connected to the internet. Or maybe not, and the same bug occurs because, say, the connection to the server closes prematurely for some reason, and Piped is unable to reconnect as described above.

Please create a new issue as this is caused by a different issue than the one from this issue originally.

**Comment by RetroAbstract** [comment] 2023-02-26 14:39
I'm still experiencing this issue, even more that before. I've tried with LibreWolf, with a hardened Firefox & with a vanilla Firefox profile and they all have the same outcome, 90% of the time the video I'm watching will randomly halt and enter infinite buffering at any point during playback no matter how long or short the video is.

> Closing due to being unable to reproduce this issue.

What browser were you using when attempting to reproduce the issue?
