### ISSUE TITLE
it is saying this and it will not let me watch a video

### ISSUE THREAD

**Issue by 372405** [TeamPiped/Piped#3495] opened 2024-03-21 18:54 UTC
### Official Instance

- [x] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

![Screenshot 2024-03-21 2 52 17 PM](https://github.com/TeamPiped/Piped/assets/130566973/21bed68b-a0e4-46aa-8c23-9e82af7a8c20)

### To Reproduce

![Screenshot 2024-03-21 2 52 17 PM](https://github.com/TeamPiped/Piped/assets/130566973/125837b5-8dcd-4476-8d51-0f3a6fadc075)

### Expected behavior

![Screenshot 2024-03-21 2 52 17 PM](https://github.com/TeamPiped/Piped/assets/130566973/6b980705-760c-46eb-abee-3a2ace71e471)

### Logs/Errors

![Screenshot 2024-03-21 2 52 17 PM](https://github.com/TeamPiped/Piped/assets/130566973/a39d1327-3920-4546-8164-54c26c900908)

### Browser, and OS with Version.

![Screenshot 2024-03-21 2 52 17 PM](https://github.com/TeamPiped/Piped/assets/130566973/eb7370eb-ad21-4737-8e0f-44a93c8b4b05)

### Additional context

![Screenshot 2024-03-21 2 52 17 PM](https://github.com/TeamPiped/Piped/assets/130566973/35e3cca9-e3a2-4079-bd43-efe0aa51bfa6)

**Comment by Bnyro** [comment] 2024-03-21 19:35
Duplicate of https://github.com/TeamPiped/Piped/issues/2915

**Closed by Bnyro** 2024-03-21 19:35 UTC
Labels: bug
