### ISSUE TITLE
[Feature Request] Playlists

### ISSUE THREAD

**Issue by TanKot** [TeamPiped/Piped#930] opened 2022-03-23 07:35 UTC
Please add playlist functionality to piped, this is the only thing that's keeping me from using piped as it is very helpful on a daily basis.

**Comment by Mennaruuk** [comment] 2022-03-27 20:29
#631

**Comment by TanKot** [comment] 2022-03-28 05:12
Sorry, didn’t notice

**Comment by FireMasterK** [comment] 2022-03-30 22:29
Duplicate of #358

**Closed** 2022-03-30 22:29 UTC
