### ISSUE TITLE
Failed with error code 1002, see logs for more info

### ISSUE THREAD

**Issue by amogusussy** [TeamPiped/Piped#2970] opened 2023-09-21 15:30 UTC
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

When ever I try to watch a video, this error message shows up:
![image](https://github.com/TeamPiped/Piped/assets/83502633/40a22cba-4f1f-45c8-96f5-be0c3e680896)

### To Reproduce

Open any  link on piped.video, piped.kavin.rocks, piped.yt, etc.
That error message shows up.

### Expected behavior

It should load.

### Logs/Errors

From the console:
```
Object { severity: 2, category: 1, code: 1002, data: (3) […], handled: false, message: "Shaka Error 1002", stack: "x@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:22922\nCS/<@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:391789\nMr@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4167\nqy/this.throw@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4560\nn@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4725\npromise callback*o@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4824\nXy/<@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4845\nXy@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4741\nI@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4879\nCS@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:391021\nSs@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:390610\nsf/<@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:74127\nU1@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:70561\nNe.prototype.ra/n/<@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:70341\npromise callback*Ne.prototype.ra@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:70479\nsf@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:74074\nsf/<@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:74946\nU1@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:70561\nNe.prototype.ra/n/<@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:70341\npromise callback*Ne.prototype.ra@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:70479\nsf@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:74452\nf.request/u<@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:72966\nU1@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:70561\nNe.prototype.ra/n/<@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:70341\npromise callback*Ne.prototype.ra@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:70479\nf.request@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:72945\nU4/<@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:341053\nMr@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4167\nqy/this.next@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4465\nXy/<@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4848\nXy@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4741\nI@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4879\nU4@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:340952\nv@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:334279\nog/<@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:305393\nMr@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4167\nqy/this.next@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4465\nXy/<@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4848\nXy@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4741\nI@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4879\nog@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:305225\nyc@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:305127\nN4/k.createSegmentIndex/<@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:336246\nMr@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4167\nqy/this.next@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4465\nXy/<@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4848\nXy@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4741\nI@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4879\nN4/k.createSegmentIndex@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:336182\nOT/<@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:201659\nMr@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4167\nqy/this.next@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4465\nXy/<@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4848\nXy@https://piped.video/assets/shaka-player.ui-7171c67c.js:1:4741\n" }
WatchVideo-4e4c0bb0.js:1:10931
```

### Browser, and OS with Version.

Librewolf on Void Linux

**Comment by saenglert** [comment] 2023-09-21 18:35
The problem appears to be caused by `https://pipedproxy-cwl.kavin.rocks/videoplayback` not providing the necessary [Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin).
![grafik](https://github.com/TeamPiped/Piped/assets/6491588/a7c9e258-fca2-4d23-ad03-d0af320877f2)

**Comment by jj2232** [comment] 2023-09-21 19:49
Error code 1002 see logs for more info keeps showing up ![image](https://github.com/TeamPiped/Piped/assets/99892733/c4e658f9-7578-4914-8430-9915c91d063d)

**Comment by Bnyro** [comment] 2023-09-22 06:11
Duplicate of #2915

**Closed by Bnyro** 2023-09-22 06:11 UTC
Labels: bug
