### ISSUE TITLE
video is shown as h264 quality even after selecting av1 

### ISSUE THREAD

**Issue by rezad1393** [TeamPiped/Piped#3186] opened 2023-11-27 10:07 UTC
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

recently videos is shown h264 quality instead of av1

### To Reproduce

1-go prefs and select codec as av1
2-go to https://youtu.be/X7Y1dkNVNBc 
3- go to https://piped.video/watch?v=X7Y1dkNVNBc
compare quality at 480p

piped video shows h264 quality

### Expected behavior

piped video should show av1 quality

### Browser, and OS with Version.

firefox 120
archlinux 64

**Comment by Bnyro** [comment] 2024-05-04 15:00
Duplicate of https://github.com/TeamPiped/Piped/issues/2658

**Closed by Bnyro** 2024-05-04 15:00 UTC
Labels: bug
