### ISSUE TITLE
No instances selectable from the dropdown menu, videos not playing

### ISSUE THREAD

**Issue by Frengo7** [TeamPiped/Piped#2822] opened 2023-08-16 18:50 UTC
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

No instances are selectable from the dropdown menu in Preferences and videos are not playing.
![Screenshot 2023-08-16 at 20-46-44 Piped](https://github.com/TeamPiped/Piped/assets/29547726/3c81cab5-1c7e-4d8b-98e1-b39386223c10)

### To Reproduce

1. Go to Preferences
2. Scroll down to Instances
3. Click on the arrow to open the dropdown menu

### Expected behavior

Various instances should be visible

### Browser, and OS with Version.

Firefox and Chromium, Win 10

**Comment by nick-n-dev** [comment] 2023-08-16 19:28
assuming this is due to piped-instances.kavin.rocks being down (502 error, yet again), only noticed because of a CORS error in the console.

Sadly, between the constant refreshing on page load and the general instability of instances, the usability of piped is getting worse by the week :(.

**Comment by Bnyro** [comment] 2023-08-17 06:03
The instance selection issue has been due to a temporary downtime of piped-instances.kavibn.rocks.

Duplicate of #2809

**Closed by Bnyro** 2023-08-17 06:03 UTC
Labels: bug
