### ISSUE TITLE
Some videos don't play

### ISSUE THREAD

**Issue by cheatie** [TeamPiped/Piped#2979] opened 2023-09-24 17:01 UTC
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

This [video](https://piped.mha.fi/watch?v=6BV-3yWzWcI) doesn't play on almost all instances except this [one](https://piped.privacydev.net/watch?v=6BV-3yWzWcI) it plays for a while then hangs. I haven't tested it on the official instance because it seems to be malfunctioning for me. [It](https://piped.kavin.rocks/watch?v=6BV-3yWzWcI) gives me "Failed with error 1002, see logs for more info".

### To Reproduce

Just open this link: https://piped.mha.fi/watch?v=6BV-3yWzWcI

### Expected behavior

The video should play

### Browser, and OS with Version.

I am using Mozilla Firefox 117.0.1 on Linux

**Comment by Bnyro** [comment] 2023-09-24 17:20
Duplicate of #2915

**Closed by Bnyro** 2023-09-24 17:20 UTC
Labels: bug
