### ISSUE TITLE
Onion versions of piped instances should not communicate over clearweb for anything.

### ISSUE THREAD

**Issue by barkoder** [TeamPiped/Piped#922] opened 2022-03-20 02:51 UTC
### Official Instance

- [x] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Currently, when I use [the onion instance of piped.kavin.rocks](http://piped2bbch4xslbl2ckr6k62q56kon56ffowxaqzy42ai22a4sash3ad.onion), thumbnails are being served from "pipedproxy-ams-2.kavin.rocks", video from "player.odycdn.com" and fonts from "fonts.kavin.rocks".

This really shouldn't be the case.

When I connect to an onion instance, no packet of data should traverse over the clearweb.

Thanks.

### To Reproduce

1. Open http://piped2bbch4xslbl2ckr6k62q56kon56ffowxaqzy42ai22a4sash3ad.onion/watch?v=d4EgbgTm0Bg
2. Ctrl+Shift+I to check the traffic.
3. Observe the non-onion clearweb connections.

### Expected behavior

All requests should be made over onion exclusively.

### Logs/Errors

NA

### Browser, and OS with Version.

Tor Browser 11.0.9 - https://dist.torproject.org/torbrowser/

**Comment by FireMasterK** [comment] 2022-03-20 19:19
> thumbnails are being served from "pipedproxy-ams-2.kavin.rocks"

This was a configuration issue on my end, and has now been fixed.

> fonts from "fonts.kavin.rocks"

Duplicate of #658

> video from "player.odycdn.com"

Enable "Enable Proxy for LBRY" in the preferences.

**Comment by barkoder** [comment] 2022-03-21 12:01
> This was a configuration issue on my end, and has now been fixed.

Thanks! Yes, it's been fixed.

> Enable "Enable Proxy for LBRY" in the preferences.

That didn't work for that video. I had to "Disable LBRY for streaming" in preferences to get that video to play.

Or appending `&disableLBRY=true` to video URLs.

Still, thanks!

**Comment by FireMasterK** [comment] 2022-03-21 18:19
> That didn't work for that video. I had to "Disable LBRY for streaming" in preferences to get that video to play.

This has now been fixed in https://github.com/FireMasterK/http3-ytproxy/commit/696c07b8c7935017e65ebc9c114cfa66c48fd904!

Thanks for the report.

**Comment by barkoder** [comment] 2022-04-11 17:53
Thumbnails are being served from "pipedproxy-ams-2.kavin.rocks" again.

**Comment by barkoder** [comment] 2022-04-11 23:51
Fixed again. Thanks @FireMasterK.

**Comment by barkoder** [comment] 2022-05-01 14:18
Hey, so it's happened again. Thumbnails from "pipedproxy.kavin.rocks" and video data from "pipedproxy-ams-2.kavin.rocks".

It also happened a week or so ago, but I didn't report it, but it did get resolved eventually.

**Comment by barkoder** [comment] 2022-05-07 15:05
Uh...well in a way, I suppose this issue is [now *technically* resolved](https://github.com/TeamPiped/Piped/issues/1038). :)

**Comment by barkoder** [comment] 2022-05-19 01:07
@FireMasterK Could you reopen this issue, please? It's not resolved. And sometimes when it seem like it's been fixed, it's only temporary.

I can disable the fonts and still make do, but when video data and thumbnails(arguably the most crucial components of YouTube) are being served over the clearweb, all the benefits that running an onion instance might provide, are rendered completely moot.

Please fix? Thanks!

**Comment by barkoder** [comment] 2022-06-12 20:20
@FireMasterK It's happened again.

**Comment by barkoder** [comment] 2022-07-09 22:52
@FireMasterK It's happened again.

**Comment by barkoder** [comment] 2022-07-09 22:52
@FireMasterK It's happened again.

**Comment by barkoder** [comment] 2022-07-18 22:44
@FireMasterK It's happened again.

**Comment by barkoder** [comment] 2022-09-20 23:59
Hey @FireMasterK , it's happened again.

Is there a technical explanation for this particular regression? This "configuration issue" seems to occur again and again? I'm confused as to why?  
Also a technical explanation for this may help any future onion instance runners.

It's happened about 12 times by now, though I've only reported it 7 times here.

Unfortunately yours is the only ~~working~~ onion instance of piped available.

https://yt.jae.fi shows that it has an onion available but it redirects to http://jaednoqb265pjbhnaaeemrielbyuu7d5vg56nf5cg7h7qscqquh7kdyd.onion/ which doesn't work.

Also is there some way to politely...*nudge*... instance runners into also hosting an onion version of piped?  
Ideally TLS+Onion but even regular onion without TLS would be great.

Thanks Kavin!

**Closed** 2023-01-02 21:43 UTC
Labels: bug
