### ISSUE TITLE
The only Piped instance which handles live streams is https://piped.privacydev.net/ , now and ever since other instances started to fail.

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#3407] opened 2024-02-17 14:45 UTC
The only Piped instance which handles live streams is https://piped.privacydev.net/ , now and ever since other instances started to fail.
Though, concerning this particular instance, better to choose its very api instance to another than its own : adminforge.de is excellent.
Why, I have no idea. Impossible to find an explanation. I even emailed this oddity to the owner of privacydev.net who never answered.
I've tried them all, https://piped.privacydev.net/ is the ONLY instance that does it.
Not to mention that many instances displayed on the [Piped instances page](https://github.com/TeamPiped/Piped/wiki/Instances) have been out of service for some time : why aren't they removed, at least by their owners ? Looks like they've discovered Piped, decided to join, and when their servers no longer handle Piped, they just don't care and leave their Piped instance listed : a total lack of respect. 

By the way, this bug is **not** fixed so why has this thread been moved to _closed issues_? This **is** and **remains** an **issue**. In whatever Piped instance, search i.e.for 'Sky News' and it will include in its results 'Sky News Live' which does not resolve... except, again, on https://piped.privacydev.net/

_Originally posted by @Cade66 in https://github.com/TeamPiped/Piped/issues/3090#issuecomment-1950218624_

**Comment by Cade66** [comment] 2024-03-01 00:40
@Bnyro added the `cant-reproduce` label? Is this a joke? Anyone, everyone will encounter the issue, and I was initially commenting https://github.com/TeamPiped/Piped/issues/3090#issuecomment-1950218624. What the heck is this?!

**Comment by Bnyro** [comment] 2024-03-01 09:00
Warning due to tagging team members - that's not permitted, see https://github.com/TeamPiped/Piped/blob/master/CODE_OF_CONDUCT.md.

If you want to be toxic, go to Telegram.

**Comment by Bnyro** [comment] 2024-03-01 09:04
In this case, this was a missclick - no reason to become toxic right away.

**Comment by Cade66** [comment] 2024-03-01 10:28
`Help wanted` doesn't really correspond to what I've reported, together with others whom as myself consider using Piped with live streams.
`Information wanted` would be more appropriate, should the label exist. Better : `Information begged for`, if prudery should stand as deeply non-toxic.

I think it was late October 2023 that a new development of Piped led to YouTube live streams no longer being handled. All updated instances led to the same issue and it seems that  https://piped.privacydev.net/ kept code others did not which would explain why it is -- in my experience -- the only instance that allows -- at this time -- to have live streams handled correctly. The instance's proxy is not concerned, it's the very instance which makes the difference.
This has been reported and what is wished is less an immediate solution than a word of explanation. Yet, not one word for over four months. This explains the tone of exasperation which didn't mean to be toxic even if perceived as such.

Thanks for switching the label to `Help wanted`.

**Comment by 0x24D** [comment] 2024-03-02 18:02
Piped:
```
0dd45b68c7559936e90a282de12681ccb67e15e7 is the first bad commit
commit 0dd45b68c7559936e90a282de12681ccb67e15e7
Author: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Date:   Thu Aug 31 00:41:34 2023 +0000

    fix(deps): update dependency shaka-player to v4.4.0

 package.json   | 2 +-
 pnpm-lock.yaml | 8 ++++----
 2 files changed, 5 insertions(+), 5 deletions(-)
```
shaka-player:
https://github.com/shaka-project/shaka-player/compare/v4.3.9...v4.4.0
```
eec25b2c6efc1cccc35509131c37bd4569d54b9e is the first bad commit
commit eec25b2c6efc1cccc35509131c37bd4569d54b9e
Author: Álvaro Velad Galván <ladvan91@hotmail.com>
Date:   Tue Aug 29 23:53:57 2023 +0200

    feat: Add TS transmuxer (#5386)
    
    - Allow to have multiple transmuxers, but choose only the one that is
    valid depending on whether it supports the codecs or not
    - Supported codecs: AAC, AC-3, EC-3, H.264, MPEG/MP3
    - It is prepared to allow more codecs in the future (HEVC/H.265) (no
    muxed)

 README.md                                          |  10 +-
 build/types/transmuxer                             |   3 +
 externs/shaka/codecs.js                            |  32 +
 karma.conf.js                                      |   3 +
 lib/media/media_source_engine.js                   |   6 +-
 lib/mss/mss_parser.js                              |   2 +
 lib/transmuxer/aac_transmuxer.js                   |   2 +
 lib/transmuxer/ac3_transmuxer.js                   |   2 +
 lib/transmuxer/ec3_transmuxer.js                   |   2 +
 lib/transmuxer/h264.js                             | 324 ++++++++++
 lib/transmuxer/mp3_transmuxer.js                   |   2 +
 lib/transmuxer/mpeg_ts_transmuxer.js               | 182 ++++++ 
 lib/transmuxer/transmuxer_engine.js                |  63 +-
 lib/transmuxer/ts_transmuxer.js                    | 689 +++++++++++++++++++++
 lib/util/exp_golomb.js                             |  14 +
 lib/util/mime_utils.js                             |   1 +
 lib/util/mp4_generator.js                          | 127 ++--
 lib/util/ts_parser.js                              | 213 +++++--
 shaka-player.uncompiled.js                         |   3 +
 test/media/drm_engine_unit.js                      |  12 +
 .../ChID_voices_6ch_640kbps_dd_sub_0000.ts         | Bin 0 -> 516248 bytes
 .../ChID_voices_6ch_640kbps_dd_sub_0001.ts         | Bin 0 -> 513804 bytes
 .../ChID_voices_6ch_640kbps_dd_sub_0002.ts         | Bin 0 -> 516248 bytes
 .../ChID_voices_6ch_640kbps_dd_sub_0003.ts         | Bin 0 -> 513804 bytes
 .../ChID_voices_6ch_640kbps_dd_sub_0004.ts         | Bin 0 -> 516248 bytes
 .../ChID_voices_6ch_640kbps_dd_sub_0005.ts         | Bin 0 -> 513804 bytes
 test/test/assets/hls-ts-ac3/prog_index.m3u8        |  19 +
 .../ChID_voices_6ch_256kbps_ddp_sub_0000.ts        | Bin 0 -> 212440 bytes
 .../ChID_voices_6ch_256kbps_ddp_sub_0001.ts        | Bin 0 -> 211312 bytes
 .../ChID_voices_6ch_256kbps_ddp_sub_0002.ts        | Bin 0 -> 212440 bytes
 .../ChID_voices_6ch_256kbps_ddp_sub_0003.ts        | Bin 0 -> 211312 bytes
 .../ChID_voices_6ch_256kbps_ddp_sub_0004.ts        | Bin 0 -> 212440 bytes
 .../ChID_voices_6ch_256kbps_ddp_sub_0005.ts        | Bin 0 -> 211312 bytes
 test/test/assets/hls-ts-ec3/prog_index.m3u8        |  19 +
 test/test/assets/hls-ts-mp3/manifest.m3u8          |  13 +
 test/test/assets/hls-ts-mp3/media_w239891843_0.ts  | Bin 0 -> 96256 bytes
 test/test/assets/hls-ts-mp3/media_w239891843_1.ts  | Bin 0 -> 96256 bytes
 test/test/assets/hls-ts-mp3/media_w239891843_2.ts  | Bin 0 -> 96256 bytes
 test/test/assets/hls-ts-mp3/media_w239891843_3.ts  | Bin 0 -> 96256 bytes
 test/transmuxer/transmuxer_engine_integration.js   |  13 -
 test/transmuxer/transmuxer_integration.js          |  96 +++
 41 files changed, 1693 insertions(+), 159 deletions(-)
 create mode 100644 externs/shaka/codecs.js
 create mode 100644 lib/transmuxer/h264.js
 create mode 100644 lib/transmuxer/mpeg_ts_transmuxer.js
 create mode 100644 lib/transmuxer/ts_transmuxer.js
 create mode 100644 test/test/assets/hls-ts-ac3/ChID_voices_6ch_640kbps_dd_sub_0000.ts
 create mode 100644 test/test/assets/hls-ts-ac3/ChID_voices_6ch_640kbps_dd_sub_0001.ts
 create mode 100644 test/test/assets/hls-ts-ac3/ChID_voices_6ch_640kbps_dd_sub_0002.ts
 create mode 100644 test/test/assets/hls-ts-ac3/ChID_voices_6ch_640kbps_dd_sub_0003.ts
 create mode 100644 test/test/assets/hls-ts-ac3/ChID_voices_6ch_640kbps_dd_sub_0004.ts
 create mode 100644 test/test/assets/hls-ts-ac3/ChID_voices_6ch_640kbps_dd_sub_0005.ts
 create mode 100644 test/test/assets/hls-ts-ac3/prog_index.m3u8
 create mode 100644 test/test/assets/hls-ts-ec3/ChID_voices_6ch_256kbps_ddp_sub_0000.ts
 create mode 100644 test/test/assets/hls-ts-ec3/ChID_voices_6ch_256kbps_ddp_sub_0001.ts
 create mode 100644 test/test/assets/hls-ts-ec3/ChID_voices_6ch_256kbps_ddp_sub_0002.ts
 create mode 100644 test/test/assets/hls-ts-ec3/ChID_voices_6ch_256kbps_ddp_sub_0003.ts
 create mode 100644 test/test/assets/hls-ts-ec3/ChID_voices_6ch_256kbps_ddp_sub_0004.ts
 create mode 100644 test/test/assets/hls-ts-ec3/ChID_voices_6ch_256kbps_ddp_sub_0005.ts
 create mode 100644 test/test/assets/hls-ts-ec3/prog_index.m3u8
 create mode 100644 test/test/assets/hls-ts-mp3/manifest.m3u8
 create mode 100644 test/test/assets/hls-ts-mp3/media_w239891843_0.ts
 create mode 100644 test/test/assets/hls-ts-mp3/media_w239891843_1.ts
 create mode 100644 test/test/assets/hls-ts-mp3/media_w239891843_2.ts
 create mode 100644 test/test/assets/hls-ts-mp3/media_w239891843_3.ts
```

**Comment by Bnyro** [comment] 2024-03-05 14:14
> `Help wanted` doesn't really correspond to what I've reported, together with others whom as myself consider using Piped with live streams. `Information wanted` would be more appropriate, should the label exist. Better : `Information begged for`, if prudery should stand as deeply non-toxic.
> 
> I think it was late October 2023 that a new development of Piped led to YouTube live streams no longer being handled. All updated instances led to the same issue and it seems that https://piped.privacydev.net/ kept code others did not which would explain why it is -- in my experience -- the only instance that allows -- at this time -- to have live streams handled correctly. The instance's proxy is not concerned, it's the very instance which makes the difference.
> 
> This has been reported and what is wished is less an immediate solution than a word of explanation. Yet, not one word for over four months. This explains the tone of exasperation which didn't mean to be toxic even if perceived as such.
> 
> Thanks for switching the label to `Help wanted`.
>
Thanks for your appreciation of open source work.

**Comment by Bnyro** [comment] 2024-03-05 14:15
Help wanted means external contributions to fix this welcome.

**Comment by Cade66** [comment] 2024-03-05 14:46
Open source work is worthy and appreciated as such. I guess we're all aware of the developers' work, providing for free code which helps everyone.
The point has never been to establish an arrogant customer to employee relationship, which is already and by itself an attitude of the past even in business.
Rather, the point is -- once we've emphasized on our gratitude for their work, which perhaps I've lacked to -- to consider what is common to all relationships, be they within business, friends, anyone, which is a natural wish to receive an echo, an answer to what we state : it's called a dialog.
Once you have that feeling, the one as saying "hello" and receiving no echo, not even a look, then you may sort of wonder what planet you're living on.
I started this thread not to complain of an issue not being fixed, but to express a bother due to this issue nor longer being acknowledged, sent to 'closed issues", no following-up ... and, after 4 months, I just wished to refresh this issue and hope for an echo : "What is going on?" was and remains my state of mind : nothing to do with arrogance, not to mention that being straightforward is neither arrogant nor toxic, and that being smooth by the words may hide an amount of arrogance behind the words.

**Comment by Bnyro** [comment] 2024-03-05 16:25
Fair enough. Due to the fact that I'm not that familiar with how the player works internally, I can't really help with that. Kavin is currently low in time and has other things to worry about, that's just how life is. It doesn't seem to work well on LibreTube either, so I don't think this is just a frontend issue as @0x24D supposed above.

**Comment by 0x24D** [comment] 2024-03-05 18:30
As per https://github.com/shaka-project/shaka-player/issues/6322#issuecomment-1979281593, downgrading to shaka-player v4.3.15 (and reintroducing mux.js) will resolve the livestream issue until it is resolved in the current version.

However the shaka-player downgrade causes the "Concurrent Stream Prefetch Limit" preference to stop taking effect due to the fact that the underlying shaka-player config ```streaming.segmentPrefetchLimit``` didn't exist until v4.4.x.

**Comment by Bnyro** [comment] 2024-03-14 18:50
Duplicate of #2898

**Closed by Bnyro** 2024-03-14 18:50 UTC
Labels: help wanted
