### ISSUE TITLE
Allowing users to pick a custom playback speed value

### ISSUE THREAD

**Issue by t3dium** [TeamPiped/Piped#2433] opened 2023-05-21 18:22 UTC
### Describe the feature

Having an input box on the playback speed tab where the user can enter a number for the playback speed, rather than only having the pre-determined speed options. 

### Why would this be useful to add?

On certain videos a step size of 0.25 seconds between each speed may be a bit too extreme and the user may want a more specific value instead, for e.g 1.4x rather than 1.25x or 1.5x. 

Or for scenarios where they may want to exceed 2x speed and go to 2.25 or 2.5x for e.g. There would be greater control over playback speed as you wouldn't be limited to a set number of options.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-05-14 08:20
Duplicate of https://github.com/TeamPiped/Piped/issues/923

**Closed by Bnyro** 2024-05-14 08:20 UTC
Labels: enhancement

**Comment by Bnyro** [comment] 2024-05-16 16:26
You can now press `Shift` and `s` at the same time to open a dialog which allows setting a custom playback speed.
