### ISSUE TITLE
Feed doesn't refresh even when piped proxy is disabled in Libretube

### ISSUE THREAD

**Issue by RegularBudgie** [TeamPiped/Piped#2998] opened 2023-10-01 15:28 UTC
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Subscription feed isn't updated on different instances and when piped proxy is disabled, subscriptions still aren't updated in LibreTube.

### To Reproduce

1. add channels to feed
2. Refresh it
3. Feed is incomplete
4. Visit the channel that isn't updated in feed
5. It's latest video will appear in feed afterwards 

### Expected behavior

Feed should be updated

### Browser, and OS with Version.

Libretube 0.18.1
Brave 1.58 131

**Comment by Bnyro** [comment] 2023-10-01 18:08
Duplicate of #1130

**Closed by Bnyro** 2023-10-01 18:08 UTC
Labels: bug
