### ISSUE TITLE
enque

### ISSUE THREAD

**Issue by imxade** [TeamPiped/Piped#1330] opened 2022-08-25 13:46 UTC
### Describe the feature

feature to enque multiple videos

### Why would this be useful to add?

1. I like to listen song in background which are not always same.
2. I don't wanna go back to **feed/search results** for each video, want to enque and play them all at once

### Concept(s)

![Screenshot_20220825-185846_NewPipe SponsorBlock](https://user-images.githubusercontent.com/56511165/186681371-5501423a-a54b-416e-a37e-ee69eb621a24.png)
![Screenshot_20220825-185818_Via](https://user-images.githubusercontent.com/56511165/186681405-8f8f42cd-8f00-4865-9b52-ca4f477c4272.png)

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment] 2022-08-25 13:50
A pre-requisite to this would be able to let the player pop up, so you can search for things while playing.

**Comment by Bnyro** [comment] 2022-08-28 10:37
dupe of #390

**Closed by Bnyro** 2022-08-28 10:37 UTC
Labels: enhancement
