### ISSUE TITLE
bulk unsubbing bug

### ISSUE THREAD

**Issue by asklow** [TeamPiped/Piped#1966] opened 2023-01-10 02:44 UTC
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

Unsubbing one channel randomly unsubs multiple channels.

### To Reproduce

Unsub one channel out of existing ones.

### Expected behavior

Should only unsub the one I did.

### Logs/Errors

NA

### Browser, and OS with Version.

Desktop as well as Android chrome both tested on latest versions.

### Additional context

https://user-images.githubusercontent.com/117489882/211449744-7c16a2a7-5675-4327-b183-9be5f9c65803.mp4

**Comment by Bnyro** [comment] 2023-01-10 08:45
With or without account?

**Comment by FireMasterK** [comment] 2023-01-10 08:50
I could reproduce this on Desktop on Brave, without an account.

**Comment by Bnyro** [comment] 2023-01-10 08:51
Maybe that could be the reason for #1271 too?

**Comment by FireMasterK** [comment] 2023-01-10 09:06
Yes, I believe it's a duplicate of that issue.

The problematic line of code appears to be https://github.com/TeamPiped/Piped/blob/fdf8c1dd2e17e629a91e2141885207b93d7751ed/src/main.js#LL227C36-L227C42

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice

Since we don't specify a `deleteCount`, it deletes all the items from the array by default, which is likely why we might be facing this issue.

**Comment by Bnyro** [comment] 2023-01-10 10:03
Oh, alright, that makes sense!

**Closed** 2023-01-10 18:33 UTC
Labels: bug

**Comment by IronMaltese** [comment] 2023-01-10 23:42
> #1271 description is very weird. OP claims it's reproducible only on iOS, whereas this one's consistent all over the platforms/browsers.

I’ll let you know if the issue keeps occurring, but this looks like it should fix my issue, thanks
