### ISSUE TITLE
Playback speed resets to default if right click screen

### ISSUE THREAD

**Issue by Yolakalemowa** [TeamPiped/Piped#842] opened 2022-02-19 21:52 UTC
Been happening for a while but was too lazy to reproduce to know exactly how it happened...

Finally figured out it simply happens with you right click to play/pause.

**Comment by M86xKC** [comment] 2022-04-23 18:13
Found interesting behavior for the playback reset bug

steps to reproduce:
open any video
change playback speed to 2.0x
close that tab
open another video (in a new tab)
pause then play the video with mouse/touch
playback speed resets to 1.0x

I think what is happening here is that playback rate gets reset when [both conditions evaluates to false here somehow?](https://github.com/TeamPiped/Piped/blob/9d486118515ddefd9dd7d6cf9ca60ce156515704/src/main.js#L149) and playback rate is set to the default value as [in this line](https://github.com/TeamPiped/Piped/blob/b1efd97c40136cdc459c32eaf40135a6b33b6000/src/components/VideoPlayer.vue#L512)

PS:
- this bug does not get triggered by using space or k shortcuts.
- this bug was reproducible in both firefox & chrome.

**Comment by M86xKC** [comment] 2022-04-25 16:19
is this related to https://github.com/shaka-project/shaka-player/issues/3709?

**Comment by FireMasterK** [comment] 2022-04-25 18:53
Yes, it looks like it gets reset when using the UI :thinking:

**Comment by FireMasterK** [comment] 2022-10-17 00:26
Closing this with #1573.

**Closed by FireMasterK** 2022-10-17 00:26 UTC
