### ISSUE TITLE
RSS Feeds - `pipedapi.kavin.rocks` - Invalid SSL certificate - Error code 526

### ISSUE THREAD

**Issue by xfzv** [TeamPiped/Piped#3517] opened 2024-03-28 14:04 UTC
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

As of today, all my channels RSS feeds (`https://pipedapi.kavin.rocks/feed/unauthenticated/rss?channels=<channel_id>`) fail with the following error when trying to fetch content:

```console
level=WARN msg="Unable to fetch feed" feed_url="https://pipedapi.kavin.rocks/feed/unauthenticated/rss?channels=<channel_id>" error="fetcher: unexpected status code (526 status code)"
```

I'm getting the same error when trying to visit the URL directly from a web browser:

![image](https://github.com/TeamPiped/Piped/assets/78810647/554c79b4-2b17-46ab-a151-e4b210ef15cc)

### To Reproduce

1. Go to any channel, e.g. `https://piped.video/channel/UC5UAwBUum7CPN5buc-_N1Fw`
2. Get the RSS feed URL on the right and try to subscribe to it, or open it in the browser
3. The errors mentioned above occur

### Expected behavior

The RSS feeds work

### Browser, and OS with Version.

Firefox 124.0.1

```console
% cat /etc/os-release
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.14"
```

**Comment by HarTstaRx** [comment] 2024-03-28 14:08
I'm having the same issue on desktop Firefox@latest & Chrome@latest, when login or searching the request fails with status 526 and both browsers interpret the fail as a CORS error but yeah, 526 is status code for SSL certificates, nonetheles the SSL seems to be fine?
![image](https://github.com/TeamPiped/Piped/assets/598657/d7410a6d-2881-4bbd-b610-8301579bcce4)
https://www.ssllabs.com/ssltest/analyze.html?d=pipedapi.kavin.rocks

**Comment by FireMasterK** [comment] 2024-03-28 17:40
Hello, this has been fixed! This was caused by a network outage, and I tried moving it to another server, but that didn't work well, so that's the cause of the TLS certificate error.

**Closed by FireMasterK** 2024-03-28 17:40 UTC
Labels: bug

**Comment by HarTstaRx** [comment] 2024-03-28 18:41
You guys rock, thanks for your work
