### ISSUE TITLE
Safari will not play a video after setting a specific quality

### ISSUE THREAD

**Issue by yoav-lavi** [TeamPiped/Piped#3277] opened 2023-12-23 18:59 UTC
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

I've noticed content freezing in Safari after setting the quality to anything other than "auto"
(I've also noticed a separate issue where the service worker has too many redirects in safari when trying to open a link directly)

### To Reproduce

1. Open https://piped.video/watch?v=pPa_O6F5kqs in Safari
2. Set the quality to 1080p
3. Seek or wait for it to load, the video will freeze

### Expected behavior

Allow the video to play normally

### Logs/Errors

None that I can see

### Browser, and OS with Version.

macOS Safari 17.2.1

**Comment by FireMasterK** [comment] 2023-12-24 19:00
Duplicate of #3258?

**Comment by yoav-lavi** [comment] 2023-12-25 16:09
@FireMasterK I don't think so, this reproduces only in Safari

**Comment by yoav-lavi** [comment] 2023-12-28 12:34
@FireMasterK Actually maybe it's related, I missed that this was on iOS which uses the same engine for all browsers (which is Safari).

**Comment by bagajohny** [comment] 2024-01-01 09:54
I am also facing issues with playing videos on iOS. I have tried Firefox and firefox focus browsers and the search results page loads fine but then I click on the video I see blank page with endless loading animation. Screenshot below, should I make a separate issue for this or is it included in the this same issue?

![image](https://github.com/TeamPiped/Piped/assets/101859073/93f0cfdb-9eea-46fe-b05e-645dc6574242)

**Comment by Bnyro** [comment] 2024-05-04 14:28
Closing as duplicate of https://github.com/TeamPiped/Piped/issues/3258.

@bagajohny Your issue is not related, try clearing the browser cache.

**Closed by Bnyro** 2024-05-04 14:28 UTC
Labels: bug
