### ISSUE TITLE
Web site stucks at main page with Falkon Browser

### ISSUE THREAD

**Issue by johna23-lab** [TeamPiped/Piped#3261] opened 2023-12-17 10:45 UTC
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Tried to use the site with the Falkon browser but stays in loop and never finish to load the main page, it happen with direct video too

### To Reproduce

1-Grab Falkon browser
2-Add the url piped.video
3-And there is the loop

Captured example
https://i.imgur.com/vVKQKOs.gif

### Expected behavior

Main page never finish to "sync"

### Browser, and OS with Version.

Latest Falkon browser in Void Linux

**Comment by FireMasterK** [comment] 2023-12-17 15:23
Hello, I believe this should be fixed now. This was caused by falkon to be incorrectly blocked by a firewall rule on my end. Let me know if it still persists, thanks!

**Closed by FireMasterK** 2023-12-17 15:23 UTC
Labels: bug
