### ISSUE TITLE
[FEATUER REQ] save settings on server side!

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [TeamPiped/Piped#1179] opened 2022-07-04 09:55 UTC
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Save user settings in server side so no matter how many times I clear my cookies my settings still the same not change it each time when I sign in 

### To Reproduce

1. Open piped instance 
2. Login in your account
3. Change quality settings (for example)
4. clear cookies or change browsers
5. login back to same account and boom settings are back to stock ones

### Expected behavior

Settings be saved on server side so user do not change all settings all over

### Logs/Errors

null

**Comment by Bnyro** [comment] 2022-08-28 10:36
dupe of #496

**Closed by Bnyro** 2022-08-28 10:36 UTC
Labels: bug
