### ISSUE TITLE
The video preview is blurry.

### ISSUE THREAD

**Issue by Nizami20052022** [TeamPiped/Piped#1154] opened 2022-06-25 10:52 UTC
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Log in to Piped, the video preview is blurry. It's not blurry on YouTube. This is the case with LibreTube.

### To Reproduce

1.Log in to Piped
2.The preview of the videos is blurry.

### Expected behavior

You need to find a solution to this problem.

### Logs/Errors

.

### Browser, and OS with Version.

1.Chrome browser
2.Android 11(version)

**Comment by Logomotif** [comment] 2022-06-25 11:02
I am very worried about this problem.

**Comment by Logomotif** [comment] 2022-06-25 11:04
This problem exists in the LibreTube application, because it is based on the Piped project.

**Comment by Logomotif** [comment] 2022-06-25 11:05
Only members of the piped project can solve this.

**Comment by FireMasterK** [comment] 2022-06-25 11:21
> Only members of the piped project can solve this.

Wrong, we need upstream changes in NewPipeExtractor.

I had made a PR before at: https://github.com/TeamNewPipe/NewPipeExtractor/pull/708, 

This is also a duplicate of #947

**Closed by FireMasterK** 2022-06-25 11:21 UTC
Labels: bug
