### ISSUE TITLE
Request (enhancement)

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#917] opened 2022-03-18 01:13 UTC
Please add double tap to seek, pinch to zoom and video preview thumbnail to player

**Comment by Mennaruuk** [comment] 2022-03-19 17:43
[#3303](https://github.com/shaka-project/shaka-player/issues/3303)
[#3371](https://github.com/shaka-project/shaka-player/issues/3371)

**Comment by FireMasterK** [comment] 2022-06-26 02:51
Duplicate of the issues mentioned above.

**Closed by FireMasterK** 2022-06-26 02:51 UTC
