### ISSUE TITLE
Topics don't filter through Piped

### ISSUE THREAD

**Issue by IronMaltese** [TeamPiped/Piped#858] opened 2022-02-24 18:30 UTC
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

[https://piped.kavin.rocks/channel/UCm6WwhIkHJFRGQd7ttnr9lQ](https://piped.kavin.rocks/channel/UCm6WwhIkHJFRGQd7ttnr9lQ) shows up with no content, but on youtube, the topic has playlists and content

### To Reproduce

Open a topic channel on Piped

### Expected behavior

There are two ways to solve this
1. find a way to scrape data from channel topics
2. Link or redirect directly to the topic's main channel Example: [https://piped.kavin.rocks/channel/UCuwdplPbuTFZj_64d03tSBA](https://piped.kavin.rocks/channel/UCuwdplPbuTFZj_64d03tSBA)

### Logs/Errors

N/A

### Browser, and OS with Version.

N/A

### Additional context

This is for the browser extension [Libredirect](https://github.com/libredirect/libredirect) since the topic channel shows up when redirecting from a youtube music artist link Ex: [https://music.youtube.com/channel/UCNYhhkQqeFLUc-YEDcLpSYQ](https://music.youtube.com/channel/UCNYhhkQqeFLUc-YEDcLpSYQ) to Piped

**Comment by FireMasterK** [comment] 2022-02-24 18:36
Duplicate of #802

**Closed by FireMasterK** 2022-02-24 18:36 UTC
Labels: bug
