### ISSUE TITLE
Unable to add any videos [to playlist], since they were unable to be fetched

### ISSUE THREAD

**Issue by DWolf-19** [TeamPiped/Piped#3757] opened 2024-08-13 21:06 UTC
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Unable to add videos to the playlists. I'm getting popup "Unable to add any videos, since they were unable to be fetched".

### To Reproduce

1. Open https://piped.video/
2. Try to add any video to the playlist.
3. Get this error.

### Expected behavior

1. Open https://piped.video/
2. Try to add any video to the playlist.
3. Video successfully added.

### Logs/Errors

Console and network tab in browser devtools are empty (no errors).

### Browser, and OS with Version.

Firefox 128.0.2 (Flatpak) on Fedora Linux.

### Additional context

Screenshot:
![image](https://github.com/user-attachments/assets/7b84ffbc-f2e8-485b-9362-463a7ec7765c)
Also, I've logged in to my account.

**Comment by Bnyro** [comment] 2024-08-14 07:52
Duplicate of https://github.com/TeamPiped/Piped/issues/3658

**Closed by Bnyro** 2024-08-14 07:52 UTC
Labels: bug
