### ISSUE TITLE
Request: installation guide

### ISSUE THREAD

**Issue by kontofikcyjne** [TeamPiped/Piped#311] opened 2021-07-25 19:30 UTC
Hi,

I would like to ask for more detailed installation instruction. Information that already is published isn't helping. Docker compose also isn't working. It looks like I'm missing something.

Thanks

**Comment by FireMasterK** [comment] 2021-07-27 18:06
Closing as this is a duplicate of #82.

**Closed by FireMasterK** 2021-07-27 18:06 UTC
