### ISSUE TITLE
Make it possible to change default settings

### ISSUE THREAD

**Issue by Elendil211** [TeamPiped/Piped#2442] opened 2023-05-23 08:04 UTC
### Describe your question

I'm selfhosting piped with Docker. I want to change the default settings. For example, I would like new users who visit my piped instance the first time, to get the light theme instead of the dark theme, or the next video to be played automatically.

What would be the best way to achieve this?

**Comment by FireMasterK** [comment] 2023-06-06 00:30
Duplicate of #2442

This isn't possible currently.

**Comment by Elendil211** [comment] 2023-06-14 09:56
> Duplicate of https://github.com/TeamPiped/Piped/issues/2442

That's *this* issue. Did you link the wrong issue?

> This isn't possible currently.

That's unfortunate.

**Comment by Bnyro** [comment] 2023-09-14 15:27
Closing in favor of #2903

**Closed by Bnyro** 2023-09-14 15:27 UTC
Labels: question
