### ISSUE TITLE
Low thumbnails and channel avatar picture quality both on web and android(LibreTube) client

### ISSUE THREAD

**Issue by archroid** [TeamPiped/Piped#947] opened 2022-04-01 18:18 UTC
![image](https://user-images.githubusercontent.com/50708771/161319729-cceeabe7-223a-4f7f-8354-e9e470e6e8d1.png)
![image](https://user-images.githubusercontent.com/50708771/161319853-f71a4aa1-f484-4f84-9a6d-bb2540eae2cc.png)
![image](https://user-images.githubusercontent.com/50708771/161319872-af7260b7-fff0-410e-9ee6-0141f2db90f0.png)

Low thumbnails and channel avatar picture quality both on web and android(LibreTube) client

**Comment by lucamp** [comment] 2022-06-09 18:18
On the home feed I have no issue, but the miniature under a playing video are pretty bad. Screenshot are taken from LibreTube, but same issue on main site

https://piped.kavin.rocks/watch?v=mM7aBjWeMnc

**Home feed**
![Screenshot_2022-06-09-19-55-42-16_1](https://user-images.githubusercontent.com/15078341/172916372-e68a3e5f-7f21-4ea3-8adf-361025b655dd.jpg)

**Thumbnail under a playing video**
Just look at the NHK logo inside the thumbnail 
![Screenshot_2022-06-09-19-29-18-70_1](https://user-images.githubusercontent.com/15078341/172916300-8f2a9829-6bda-4db2-91fa-ee26a35bd134.jpg)

**Comment by Bnyro** [comment] 2022-08-11 10:02
Duplicate of #693

**Closed by Bnyro** 2022-08-11 10:02 UTC
