### ISSUE TITLE
[Feature_Request]

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#1191] opened 2022-07-08 11:59 UTC
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

option to filter search results through time posted :D it is already in YouTube and i hope this gets added to piped too, would be pretty useful

### To Reproduce

.

### Expected behavior

.

### Logs/Errors

.

### Browser, and OS with Version.

.

**Comment by andrei-g-git** [comment] 2022-07-09 12:59
I'm not sure if it counts as a bug but it would certainly be a handy feature to have, not just for content duration, but other filters like sorting by date, relevance, rating, views etc. Invidious has this and there's no reason why piped should fall behind, as the more popular option.

**Comment by Bnyro** [comment] 2022-07-20 16:52
dupe of #275

**Closed by Bnyro** 2022-07-20 16:52 UTC
Labels: bug
