### ISSUE TITLE
Shorts section of channel page is empty

### ISSUE THREAD

**Issue by DanielProg39** [TeamPiped/Piped#2754] opened 2023-08-03 21:04 UTC
### Official Instance

- [x] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Make no mistake: Shorts will play correctly and show up in the feed if the appropriate filter is applied. The problem is that they are not displayed in the appropriate section of the channel page. Some channels mainly make this type of video, so it's inconvenient to browse them. I've already mentioned this problem in the other thread (https://github.com/TeamPiped/Piped/issues/2487#issuecomment-1618303102), but since it hasn't been resolved in over a month now, I've decided to open a separate issue for it.

### To Reproduce

1. Open a channel page
2. Go to Shorts section
3. Void…

### Expected behavior

Videos should be shown

### Browser, and OS with Version.

Chromium/Firefox 114/115, both on desktop and mobile, also LibreTube 0.16.1

**Comment by Bnyro** [comment] 2023-08-03 21:29
Duplicate of #2624

**Closed by Bnyro** 2023-08-03 21:29 UTC
Labels: bug

**Comment by DanielProg39** [comment] 2023-08-04 19:52
> Duplicate of #2624

How had I not discovered this issue, sorry for duplicating 🤦‍♂️

**Comment by Bnyro** [comment] 2023-08-04 19:59
No worries :)
