### ISSUE TITLE
[API] store Playlists and watched history 

### ISSUE THREAD

**Issue by Kenji-1984** [TeamPiped/Piped#1283] opened 2022-08-07 13:19 UTC
### Describe the feature

Im a User of the project Libretube.
The data of User watched list and playlists are stored localy.
I asked the developer He told me there is no way at the Moment with the API to sync the data to the instance.

Please add such functions. 

### Why would this be useful to add?

IT helpes to sync the data on multiple Devices. 

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment] 2022-08-07 14:28
Playlists are not stored locally, however watch history is.

**Comment by Kenji-1984** [comment] 2022-08-07 14:35
May you can implement to store watch history on instance please?

**Comment by MaximilianGaedig** [comment] 2022-08-08 11:54
I would say this is a welcome feature by me aswell, it's the one thing YouTube has over piped that is important to me, syncing video watch progress, so I can continue watching on another device

**Comment by Bnyro** [comment] 2022-08-11 10:06
Duplicate of #371

**Closed by Bnyro** 2022-08-11 10:06 UTC
Labels: enhancement

**Comment by xIUPITERx** [comment] 2023-04-05 22:08
> I would say this is a welcome feature by me aswell, it's the one thing YouTube has over piped that is important to me, syncing video watch progress, so I can continue watching on another device

Wait, you can do that on YouTube?
