### ISSUE TITLE
Embeds are very very bad

### ISSUE THREAD

**Issue by TanKot** [TeamPiped/Piped#890] opened 2022-03-10 16:50 UTC
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Embeds of links are bad.
It just shows piped.kavin.rocks as the embed rather than the video.
I tried the same on invidious and they have embeds like YouTube does.
Could you please change backend stuff to make embeds look good?

### To Reproduce

Open Piped and try to share a video.
This will be the embed:
![49D48B97-357F-448F-BD7E-E8689B85DED6](https://user-images.githubusercontent.com/77598655/157713140-feaf0de9-2494-4258-b0e9-4d7700c7b5b4.jpeg)

I changed the server from piped to invidious to get this beautiful and normal embed:
![E40C22E9-D748-4089-AE55-D5C9774A7EA5](https://user-images.githubusercontent.com/77598655/157713312-8899ff3c-5233-418d-a30e-27b0b0d81aff.jpeg)

### Expected behavior

A good embed

### Logs/Errors

Bad embed that isn’t actually even an embed…

**Comment by mmjee** [comment] 2022-03-10 18:25
If I understand right this is just a OG embed fail.

Piped is a SPA application and therefore if the service doesn't support rendering the URL in a real browser you won't get an embed, and Piped as of now doesn't generate one either. But it's possible to run it under something like rendertron and prerender to allow bots access to the metadata even if it doesn't run it in a real browser. (If Piped adds support for generating metadata)

**Comment by TanKot** [comment] 2022-03-11 07:57
Ah Okay
Piped Authors, any plans on making the embeds actual embeds?

**Comment by nityy** [comment] 2022-03-13 06:59
probably a duplicate of #864

**Comment by TanKot** [comment] 2022-03-13 13:38
I didn’t even know that existed…
You should think both ways dude

**Comment by Latrolage** [comment] 2022-04-15 14:57
I think it's related to #535

**Comment by lordkitsuna** [comment] 2022-06-13 00:35
This is a very important missing feature. It makes piped a non-starter for pretty much any casual user who would otherwise be fine with it. Sharing links on things like discord is how youtube gets used now and not having an embed is just death of the platform most people won't look at a link without one.

Even if it ends up being a proxy that steals a preview from the YouTube page or something. It's definitely the absolute most important missing feature for using piped regularly

**Comment by FireMasterK** [comment] 2022-07-19 18:14
Duplicate of #864

**Closed by FireMasterK** 2022-07-19 18:14 UTC
Labels: bug

**Comment by ACK-J** [comment] 2022-07-30 18:22
+1 on this. I understand piped is a SPA but is there any workaround such as what @mmjee suggested?

**Comment by mmjee** [comment] 2022-07-30 19:57
Important to note that individual instance operators can fix this problem through by 1. Patching Piped to generate metadata and 2. Running it through Prerender or Rendertron. My instances that run Piped Material do that for example.

https://piped-material.ftp.sh/watch?v=dQw4w9WgXcQ embeds fine.

Kavin might find it reasonable to add support for generating metadata for the instances that choose to run it through a browser engine, even if his instances don't do that.

Regards,

**Comment by lordkitsuna** [comment] 2022-08-09 04:54
> Important to note that individual instance operators can fix this problem through by 1. Patching Piped to generate metadata and 2. Running it through Prerender or Rendertron. My instances that run Piped Material do that for example. https://piped-material.ftp.sh/watch?v=dQw4w9WgXcQ embeds fine. Kavin might find it reasonable to add support for generating metadata for the instances that choose to run it through a browser engine, even if his instances don't do that. Regards,
> […](#)
> On 30/07/22 23:52, Jack wrote: +1 on this. I understand piped is a SPA but is there any workaround such as what @mmjee suggested?

you wouldn't happen to have any guide or know of one for getting that setup would you? would love to be able to do that on my instance (docker) but have not used rendertron and am not entirely sure what all would be needed

**Comment by mmjee** [comment] 2022-08-09 05:34
Piped as of now doesn't generate HTML metadata, so it's not possible. If Kavin decides to add support, you can for instance use my prerender-boilerplate (https://github.com/mmjee/prerender-boilerplate) to easily add Prerender support. Do keep in mind this involves running a whole browser for the crawler requests. (Or use Piped-Material if it's really that important for you, it generates metadata)

Regards,
