### ISSUE TITLE
Channel Tabs

### ISSUE THREAD

**Issue by trymeouteh** [TeamPiped/Piped#802] opened 2022-02-08 04:24 UTC
Please add the tabs that are available on channels youtube page such as Videos, Playlists, Community, Channels, About

**Comment by Loki-L1130** [comment] 2022-02-08 07:47
This is pretty much the 
Duplicate of #550

**Comment by FireMasterK** [comment] 2022-02-08 10:58
I'd want this to be added upstream in NewPipeExtractor first - https://github.com/TeamNewPipe/NewPipeExtractor/issues/501

**Closed by FireMasterK** 2022-02-08 10:58 UTC
