### ISSUE TITLE
Piped Backend Giving 404 when Ran without Reverse Proxy

### ISSUE THREAD

**Issue by jollySleeper** [TeamPiped/Piped#3544] opened 2024-04-08 12:52 UTC
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Hi, 
Kavin & Devs thank you for this amazing project.
I just wanted to test out the self-hosting experience, so with all my laziness I gave it a shot without having a Reverse Proxy & with Podman and not Docker using the steps mentioned below.

### Docker-Compose Translated
```bash
podman pull docker.io/postgres:15
podman pull docker.io/1337kavin/piped:latest
podman pull docker.io/1337kavin/piped-frontend:latest

podman pod create -p 8090:80 -p 8091:8080 --name piped 

# root mode
#--user $(id -u):$(id -g) \
podman run \
 --pod piped \
 --restart unless-stopped \
 -v ~/selfhost/piped/postgres-data:/var/lib/postgresql/data \
 --env-file ~/selfhost/piped/postgres-env-file \
 --name postgres \
 docker.io/postgres:15

# root mode
#--user $(id -u):$(id -g) \
podman run \
 --pod piped \
 --restart unless-stopped \
 -v ~/selfhost/piped/api-config.properties:/app/config.properties:ro \
 --name piped-api \
 docker.io/1337kavin/piped:latest

# root mode
#--user $(id -u):$(id -g) \
podman run \
 --pod piped \
 --restart unless-stopped \
 -v ~/selfhost/piped/entrypoint.sh:/entrypoint.sh \
 --name piped-frontend \
 docker.io/1337kavin/piped-frontend:latest
```

### postgress-env-file
```
POSTGRES_DB=piped
POSTGRES_USER=piped
POSTGRES_PASSWORD=temp1234
```

### api-config.properties
```
# The port to Listen on.
PORT: 8080

# The number of workers to use for the server
HTTP_WORKERS: 2

# Proxy
PROXY_PART: http://192.168.1.235:8091
# Outgoing HTTP Proxy - eg: 127.0.0.1:8118
#HTTP_PROXY: 127.0.0.1:8118

# Captcha Parameters
#CAPTCHA_BASE_URL: https://api.capmonster.cloud/
#CAPTCHA_API_KEY: INSERT_HERE

# Public API URL
API_URL: http://192.168.1.235:8091


# Public Frontend URL
FRONTEND_URL: http://192.168.1.235:8090

# Enable haveibeenpwned compromised password API
COMPROMISED_PASSWORD_CHECK: false

# Disable Registration
DISABLE_REGISTRATION: false

# Feed Retention Time in Days
FEED_RETENTION: 30

# Hibernate properties
hibernate.connection.url: jdbc:postgresql://postgres:5432/piped
hibernate.connection.driver_class: org.postgresql.Driver
hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.username: piped
hibernate.connection.password: temp1234 
```

### entrypoint.sh
```
#!/bin/ash
echo "Piped Frontend Started"
ash -c 'sed -i s/pipedapi.kavin.rocks/192.168.1.235:8091/g /usr/share/nginx/html/assets/* && /docker-entrypoint.sh && nginx -g "daemon off;
```

### I'm getting multiple 404's and connection errors of backend(api)
> URL: http://192.168.1.235:8090/trending
![image](https://github.com/TeamPiped/Piped/assets/87367804/7a29ee48-d3bd-4988-95c0-8bdf61647d1f)

> URL: http://192.168.1.235:8090/watch?v=mt81k1z4VIw
![image](https://github.com/TeamPiped/Piped/assets/87367804/4574b31d-a4c0-4b0b-99c8-b997665c45a1)

You can see in the above image that most of the api path is giving 404.

Please help :pray:  (sorry for not using the script provided & not using rev-proxy)

### To Reproduce

Open URL http://192.168.1.235:8090/trending

### Expected behavior

This should have worked as when used other api instance it is working.

### Browser, and OS with Version.

Using Podman
```
$ podman -v
podman version 4.9.3
```

### Additional context

This 2 issues are somewhat similar but one was issue with DB https://github.com/TeamPiped/Piped/issues/1193 & other was I guess similar to this https://github.com/TeamPiped/Piped/issues/847

So, is it the case that piped won't work without reverse proxy?

**Comment by jollySleeper** [comment] 2024-04-08 14:28
One thing I noticed is, it is happening when HTML is being requested.
Maybe I have messed up somewhere??

**Comment by matt-laird** [comment] 2024-04-08 20:28
Your IP probably blacklisted on YT side - refer to documentation https://docs.piped.video/docs/self-hosting/#:~:text=Because%20YouTube%20tends%20to%20ban%20IP%20addresses%2C%20it%20is%20recommended%20to%20either
Also, since you are using Podman and no reverse proxy, it is up to you to figure out what the cause of your problems are, since you are not following what is outlined in the docs, technically you are on your own.

**Comment by FireMasterK** [comment] 2024-04-09 00:52
Hi, this is because you're not running [piped-proxy](https://github.com/TeamPiped/piped-proxy) and your proxy (the `/videoplayback` requests) is actually pointing to the backend.

See these:
https://github.com/TeamPiped/Piped-Docker/blob/main/template/ytproxy.conf
https://github.com/TeamPiped/Piped-Docker/blob/main/template/pipedproxy.conf
https://github.com/TeamPiped/Piped-Docker/blob/49b98cbeb3a1d8042ccd384b81976793bcd06a53/template/docker-compose.nginx.yml#L11-L18

I will close this issue since we don't currently support these kinds of setups here, but if you do require more help, feel free to join the public rooms!

**Closed by FireMasterK** 2024-04-09 00:52 UTC
Labels: bug

**Comment by jollySleeper** [comment] 2024-04-09 06:51
Yes @matt-laird I know I'm on my own on this one and to be honest I followed the doc but didn't want to use it just for my local setup/local network as I'm not planning on hosting a Public Instance, I just wanted NewPipe alternative for my desktop and for now I'm okay with exposing my IP to YT as is the case with NewPipe. Also, to be frank it's a skill issue from my side to understand the AIO scripts.

@FireMasterK are you saying that Piped only runs with piped-proxy & it isn't possible to run it without it? (Saw the issue somewhere where they wanted to run without proxy, don't remember now)

Will join the group to try out my current setup because like a stated above, I just want it for my local network as a possible replacement for NewPipe and the doc mentions AIO Script which is for setting up Public Instances. My scope is different than this Project's scope.(many would like to selfhost for thier PCs had it been a tad easier for begineers like me).

Anyways thank you so much for your work Kavin. Huge fan.
Thanks for the reply <3
