### ISSUE TITLE
Shorts not recognized as Shorts in feed anymore?

### ISSUE THREAD

**Issue by Ammako** [TeamPiped/Piped#2519] opened 2023-06-10 04:28 UTC
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

I filter out Shorts from my feed because I'm not interested. but as of two days ago, shorts started showing up on the Videos feed anyway, and they don't show on the Shorts feed, because they aren't being properly tagged as Shorts.

<details>
  <summary>Screenshot:</summary>

  ![image](https://github.com/TeamPiped/Piped/assets/108308111/09d2c06a-0527-49c5-9413-e42a0e33592f)

</details>

### To Reproduce

1. Be subscribed to channels that publish shorts
2. Filter feed to Videos only
3. Be annoyed that Shorts show up there anyway

### Expected behavior

Shorts should be getting flagged as such, so that they can be properly filtered.

### Additional context

Newpipe doesn't seem to support shorts (?) so I can't check if it might be an extractor error. but the shorts do get properly sorted into the Shorts tab on the channel pages. So Piped does understand in some way or another that those are supposed to be Shorts.

I loaded my subscriptions list on piped.video (no data from it saved in my browser prior to this), and older shorts are properly marked as Shorts retroactively, while the same newer shorts don't. It's not a channel-specific problem because the same channel will have both shorts that are marked, and newer ones that aren't. So I guess there must be something Youtube is doing with newer shorts that makes Piped fail to properly mark them, despite being able to properly mark older ones.

**Comment by Bnyro** [comment] 2023-06-10 12:34
I can confirm the issue. Since there have been some changes to the feed lately, it might have been caused by that.

In the search results, videos are still marked as shorts properly, for example the first result at https://pipedapi.kavin.rocks/search?q=tv%20total%20sprachpolizei&filter=all.

So we should likely have a look at the most recent commits at the backend.

**Closed** 2023-06-10 21:08 UTC
Labels: bug
