### ISSUE TITLE
Is it possible a shadow banning here?

### ISSUE THREAD

**Issue by luckkmaxx** [TeamPiped/Piped#2501] opened 2023-06-04 20:14 UTC
### Describe your question

I suscribed a channel wich is the only one I dont get in feed unless I enter to the channel page.
https://www.youtube.com/channel/UCWI70VlhoBiCvhmDMQle9UA

**Comment by FireMasterK** [comment] 2023-06-04 21:51
Duplicate of #1130

**Closed by FireMasterK** 2023-06-04 21:51 UTC
Labels: question
