### ISSUE TITLE
Channel RSS Feeds

### ISSUE THREAD

**Issue by trymeouteh** [TeamPiped/Piped#801] opened 2022-02-08 04:22 UTC
Please add the ability to have RSS feeds for any YouTube Channel with a RSS feed button appearing on the homepage of every channel.

**Comment by Loki-L1130** [comment] 2022-02-08 07:48
See discussion here : https://github.com/TeamPiped/Piped/issues/321

**Comment by Loki-L1130** [comment] 2022-02-08 07:53
Duplicate of #321

**Comment by FireMasterK** [comment] 2022-02-08 12:40
This won't be done since it's just inefficient to do so on the backend, you should either use the RSS feed, which can be seen on the feed page when logged in, or just use YouTube's RSS URLs.

**Closed by FireMasterK** 2022-02-08 12:40 UTC

**Comment by trymeouteh** [comment] 2022-02-08 23:06
I did not know that the Youtube channel URL works as a RSS feed. Maybe adding a RSS feed button which will just copy the YouTube channel URL (Not the piped channel URL)?

**Comment by FireMasterK** [comment] 2022-02-10 15:22
You can see: https://www.youtube.com/feeds/videos.xml?channel_id=UCLXo7UDZvByw2ixzpQCufnA for example, I don't think implementing this is a good idea, unless more people request for it.
