### ISSUE TITLE
All subscriptions gone and no login

### ISSUE THREAD

**Issue by Inrumpo** [TeamPiped/Piped#784] opened 2022-02-03 20:53 UTC
Today I started `https://piped.kavin.rocks/subscriptions` on my iPad. All my subscriptions are gone. 
Then I checked on my PC. The same thing: Not a single subscription.

I can't provide any information on how to reproduce this since I didn't do anything special.

I tried to log out and in again. Unfortunately, that doesn't work either. I can't click the `Login` button. It simply doesn't do anything.
I tested this on Android 12, iOS 15 and Windows 10.

**Comment by FireMasterK** [comment] 2022-02-03 22:11
Can you try clearing site data and try again?

**Comment by Veloxization** [comment] 2022-02-04 00:47
I have the same issue. I did a little bit of diagnostics and there seems to be an error with logins specifically. The POST request to `https://pipedapi.kavin.rocks/login`, which I assume is the API judging by the URL, fails with the following message: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pipedapi.kavin.rocks/login. (Reason: CORS request did not succeed).`

It does not seem to be related to a browser extension as it repeats on completely clean, extensionless browsers. It's also likely not browser-related as it repeats on both Chromium and Firefox. May be an issue on the backend, uncertain.

**Comment by FireMasterK** [comment] 2022-02-04 01:51
Could you copy and send the response from the network tab? That should help investigate what's wrong

**Comment by Kattox** [comment] 2022-02-04 07:28
I'm see the same issue
On firefox in the response section I get the error 
`Response body is not available to scripts (Reason: CORS Missing Allow Origin)` alongside [this link](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin)
In both chromium and firefox I could not see the response data.

**Comment by wadbr** [comment] 2022-02-04 10:33
Same error, the subsciption json is just empty when exported 

`{"app_version":"","app_version_int":0,"subscriptions":[]}`

**Comment by Veloxization** [comment] 2022-02-04 11:15
> Could you copy and send the response from the network tab? That should help investigate what's wrong

Like stated by the others, the response was completely blank. Either way, the logins seem to be working now and subscriptions load no problem. If I manage to reproduce this I'll report back at a later date with more information, if at all possible.

**Comment by realAbitbol** [comment] 2022-02-04 12:51
Still doesn't work for me when set to official server kavin.rocks (official) in preferences

<img width="640" alt="Capture d’écran 2022-02-04 à 13 50 32" src="https://user-images.githubusercontent.com/73762857/152532071-4ce00281-4601-4797-9a83-886dec20a49b.png">

**Comment by FireMasterK** [comment] 2022-02-04 20:41
There seemed to have been a server that was down, this is now fixed! It shouldn't happen anymore :)

**Closed by FireMasterK** 2022-02-04 20:41 UTC

**Comment by wadbr** [comment] 2022-06-05 09:49
@mizzunet there's a json export import feature already in the `/subscription` page
