### ISSUE TITLE
Sort the playlist and the videos in the playlist.

### ISSUE THREAD

**Issue by Broniy** [TeamPiped/Piped#1305] opened 2022-08-15 11:36 UTC
### Describe the feature

Sort videos in Playlist and Playlist.

### Why would this be useful to add?

Sort playlist:
1.A-Z
2.Last added.

Sort the videos in the playlist:
1.Date added(most recent)
2.Date added(the oldest)
3.Release date(most recent)
4.Release date(the oldest)
5.The most popular

### Concept(s)

There is no need to.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-08-27 16:50
dupe of #964

**Closed by Bnyro** 2022-08-27 16:50 UTC
Labels: enhancement
