### ISSUE TITLE
Filters or Order by date during search

### ISSUE THREAD

**Issue by nick008a** [TeamPiped/Piped#1836] opened 2022-11-29 00:46 UTC
### Describe the feature

Allow filtering by date or ordering by date during search.

### Why would this be useful to add?

Find recent video easily.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment] 2022-11-29 00:59
Duplicate of #1376

**Closed** 2022-11-29 00:59 UTC
Labels: enhancement
