### ISSUE TITLE
[Question] Pattern for redirecting embedded YT videos to Piped redirect

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#786] opened 2022-02-04 14:11 UTC
Hi,

Both _**Privacy Redirect**_ or _**LibRedirect**_ browser _extensions_ include redirecting YouTube videos, though to Invidious instances but selecting a Piped instance works as fine, embedded YT videos included.

I use neither of these extensions because I handle redirections (Instagram, Medium, Reddit, Twitter) as well as YouTube with the REDIRECT extension (Firefox).
I have a REDIRECT pattern for YouTube videos which works fine (see hereafter) though may miss exceptions. This pattern is not for embedded YT videos, it wouldn't work, it applies only to _Main Window (address bar)_ whilst a dedicated pattern to embedded YT videos should include _IFrames_ in place of _Main Window_.

It is this pattern for IFrames I'm searching for. I'm not sufficiently skilled to elaborate it myself. Help would be most appreciated.
Here's the filter I use with the REDIRECT extension to redirect all YT videos (except embedded/IFrame ones) :

![3](https://user-images.githubusercontent.com/65161029/152542708-fdb0ce43-0964-4abe-9140-8380537f6017.jpg)

What i'm eagerly aiming at is to use REDIRECT for embedded YT videos. Muchas gracias if you can help with that!

**Comment by FireMasterK** [comment] 2022-02-05 01:58
You should enable the "IFrames" option too, that should help.

**Comment by Cade66** [comment] 2022-02-05 10:10
> You should enable the "IFrames" option too, that should help.

That's what I meant went I wrote above, "_I have a REDIRECT pattern for YouTube videos which works fine (see hereafter) though may miss exceptions. This pattern is not for embedded YT videos, it wouldn't work, it applies only to Main Window (address bar) **whilst a dedicated pattern to embedded YT videos should include IFrames in place of Main Window**._"

I've come up with a new pattern dedicated to embedded (IFramed) YouTube videos which works (testing page) on `https://wn.com/#/live` but I'm far from certain that this pattern is sufficiently elaborated. But even with _Privacy Redirect_ and _LibRedirect_ extensions (replacing an _Invidious_ instance with `piped.kavin.rocks`) some connections to YouTube images are still established (i.e. `i.ytimg.com` in the case of `https://wn.com/#/live`) ...

![4](https://user-images.githubusercontent.com/65161029/152637327-397f9e98-1747-4da6-92e3-7cb3b2fc6943.jpg)

For the time being I'll avoid redirecting embedded YouTube videos. I'm not too fond of approximations.

**Comment by Loki-L1130** [comment] 2022-02-05 12:07
> But even with Privacy Redirect and LibRedirect extensions (replacing an Invidious instance with piped.kavin.rocks) some connections to YouTube images are still established (i.e. i.ytimg.com in the case of https://wn.com/#/live) ...

This is a valid argument.

**Comment by ManeraKai** [comment] 2022-02-05 12:53
> ome connections to YouTube images are still established (i.e. i.ytimg.com in the case of https://wn.com/#/live)

I didn't know that this url exists too, added it to the targets list: github.com/libredirect/libredirect/commit/23be155b204ae2806e5ff276a3c27b67f50748bc

**Comment by ManeraKai** [comment] 2022-02-05 13:02
Also, added a hard cancel to requests that can't be handled by either invidious or piped

**Comment by Loki-L1130** [comment] 2022-02-05 13:15
I didn't know that this url exists too, added it to the targets list: [libredirect/libredirect@23be155](https://github.com/libredirect/libredirect/commit/23be155b204ae2806e5ff276a3c27b67f50748bc)

You made the code to Block Google Connections - Am I getting it right ?

**Comment by ManeraKai** [comment] 2022-02-05 13:32
I made it block the every domain that matches this list in youtube's case: https://github.com/libredirect/libredirect/blob/master/src/assets/javascripts/helpers/youtube/youtube.js#L7-L19
All this **IF** the redirection was enabled.

**Comment by Cade66** [comment] 2022-02-05 13:34
Redirecting embedded videos with no connection to the video issuer, especially YouTube ones, is obviously an extremely tough challenge if aiming 100% reliability. Simple embedded links are easy, others are extremely complicated, i.e. those of `france24.com` which not only access YouTube images servers but `youtube.com` itself **EVEN** if the redirect is functional. As I see it (or wish it) a true redirection means that the redirection should work even if the redirected source is blocked at the OS level (not within the browser because the redirector code needs the called source data) ... and this is extremely hard to achieve, not sure (but I'm a neophyte) it is even possible.

I'll consider that tools (Piped, Invidious, LibRedirct) which redirect YouTube links (live ones included) and channels correctly are by themselves most worthy.
Of course, if the aim of redirecting is not only for page rendering speed, not only for the fact that such redirections avoid privacy+1 data to be sent to YT, but as well avoiding any contact (cyber, not social!) with Big YT, then we're dealing with dreams, I guess.

**Comment by stephenhawk8054** [comment] 2022-02-14 09:44
I see, I think you should provide exact URL and steps to reproduce so extensions' maintainers can address this issue.

From this URL, I guess it's because of to the tag `preconnect`:
`https://www.france24.com/en/europe/20220214-us-reaffirms-warning-russia-could-invade-ukraine-as-scholz-heads-to-kyiv`

```html
<link rel="preconnect" href="https://www.youtube.com/iframe_api" as="script"/>
```

To address this, I think it's related to `webRequest.filterResponseData()` API but only Firefox supports it now

[https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/filterResponseData](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/filterResponseData)

Similar to how ublock is dealing with by [HTML Filtering](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#html-filters). 
Related ublock's issue: [https://github.com/uBlockOrigin/uBlock-issues/issues/548](https://github.com/uBlockOrigin/uBlock-issues/issues/548).

Chromium still has problems of preventing the preconnections here, while Firefox is more reliable.
[https://github.com/gorhill/uBlock/issues/3219](https://github.com/gorhill/uBlock/issues/3219)
[https://bugs.chromium.org/p/chromium/issues/detail?id=785125](https://bugs.chromium.org/p/chromium/issues/detail?id=785125)

I'm not sure if it can be addressed by Libredirect, but sorry for tagging you @ManeraKai . I'll leave the references here in case you want to look over it.

**Comment by Cade66** [comment] 2022-02-14 10:10
> I see, I think you should provide exact URL and steps to reproduce so extensions' maintainers can address this issue

The urls are visible on the screenshots, but to be explicit : 
`https://www.france24.com/fr/europe/20220214-crise-ukrainienne-le-chancelier-allemand-olaf-scholz-attendu-à-kiev`
`https://fr.euronews.com/live`

In fact, all YouTube **_embedded_** videos (live or not) on both `https://www.france24.com/` and `https://fr.euronews.com/`

To reproduce : 
redirect YouTube embedded videos with either LibRedirect, Privacy Redirect or Redirector (with a valid pattern of course)
open above-mentioned links

Many thanks for your analysis; though i'm far from being a techie I'd be willing to understand the `webRequest.filterResponseData()` API culprit.

> I'm not sure if it can be addressed by Libredirect

I'm not sure _**any**_ redirect code can handle this.
That's what I had in mind when I wrote above (sorry for quoting myself) :

> Of course, if the aim of redirecting is not only for page rendering speed, not only for the fact that such redirections avoid privacy+1 data to be sent to YT, but as well avoiding any contact (cyber, not social!) with Big YT, then we're dealing with dreams, I guess.

This is why as much I appreciate redirecting non-embedded videos, as much I remain doubtful about the pertinence of redirecting embedded videos.

**Comment by stephenhawk8054** [comment] 2022-02-14 10:37
For helping projects' maintainers, I think it's always better to give exact URL besides screenshots or instead of mentioning it unclearly since it might give more burdens to the volunteers.

Actually redirectors can stop connections or modify the embedded links, but it would require more efforts into manipulating the sites' `view-source` and might go beyond maintainers' purposes.

I don't quite really get your definitions of **embedded** and **non-embedded** videos. Do you mean **non-embedded** is when we open the main page of `www.youtube.com`? I think redirectors address 2 types: `main frame` as when we open the websites as first party URL (for example main site of `www.youtube.com`) and `sub frame` as when websites embed the `iframe` of 3rd-party links (for example `www.youtube.com` frame in `france24.com` site).

**Comment by stephenhawk8054** [comment] 2022-02-14 11:10
So I think what you mean is the `main frame` or when `www.youtube.com` is the 1st-party URL (when we open directly in the main site). Yeah I think it's a good suggestions since more options is always better. I used to modify the code to stop it working with embeds (or `iframes`) since it's hard to see the videos' titles.

**Comment by Cade66** [comment] 2022-02-14 11:16
I agree reproducibility must be clearly explained.
I agree that embedded, hence non-embedded is ambiguous (for instance https://www.youtube.com/embed/[VIDEOID] is not embedded in my conception.
I should rather use the term IFramed/non-IFramed.

> So I think what you mean is the main frame or when www.youtube.com is the 1st-party URL (when we open directly in the main site).

Correct! I'm no techie and one of the consequences is that terminology, which is essential to explain and be understood, often lacks!

**Comment by stephenhawk8054** [comment] 2022-02-14 11:40
Actually all youtube video on other sites use the same `https://www.youtube.com/embed/[VIDEOID]` link. The difference is just how each site embeds them:

* If they just embed like

```html
<iframe src="https://www.youtube.com/embed/UTv7l6czu5s?wmode=opaque" width="560" height="315" frameborder="0" allowfullscreen="true"></iframe>
```

then no youtube connections will be fired from the website.

* However, if they use [YouTube Player API](https://developers.google.com/youtube/iframe_api_reference) to deliver the videos (similar to the case of `france24.com`), it would require `https://www.youtube.com/iframe_api` connection to be made to load the links in the form

```
https://www.youtube.com/embed/M7lc1UVf-VE?enablejsapi=1
```

and I'm not sure if it's some bugs or not that the above URL can't be blocked yet.

That's what I can see right now.

**Comment by Cade66** [comment] 2022-02-14 12:30
Got it. I considered `https://www.youtube.com/embed/[VIDEOID]` as non-embedded because assuming this format sent to the main frame when in fact can be included in an IFrame and actually is, at least most of the tiime.

`https://www.youtube.com/embed/M7lc1UVf-VE?enablejsapi=1` redirected to YouTube with my `(.*//.*)(youtube.com|youtube-nocookie.com|youtu.be|youtube.nored)/(.*)` Redirector pattern keeps the `?enablejsapi=1` of course.

Redirected to piped.kavin.rocks works, no page rendering difference with or without `?enablejsapi=1`
Redirected to yewtu.be (Invidious instance) works as well except that `?enablejsapi=1` is removed by yewtu.be

Your` /https?:\/\/(www\.|)(youtube|youtube-nocookie)\.com\/embed\/..*/` pattern doesn't include the essential `watch` ...

This can become complicated. Exceptions bother principles, as always ... and fortunately, because life is diversity and its surprises.

> However, if they use YouTube Player API to deliver the videos (similar to the case of france24.com), it would require https://www.youtube.com/iframe_api connection to be made to load the links in the form

Seems this is the major point. Not all IFramed videos use it which is why, I assume, redirecting IFramed videos is sometimes flawless, quick and 100% private. Looks like this API is the next challenge for redirectors, should it be feasible.

**Comment by ManeraKai** [comment] 2022-02-14 20:12
This is really weird. As of what I understood, you really should let the code run (Youtube Player API) before you can know which embed url it wants if you didn't want to tweak the JavaScript code.

**Closed** 2024-06-13 20:29 UTC
