### ISSUE TITLE
Add ability to self-host fonts

### ISSUE THREAD

**Issue by privacytime101** [TeamPiped/Piped#1852] opened 2022-12-04 22:08 UTC
### Describe the feature

Fonts are currently loaded from https://fonts.kavin.rocks on the majority of instances, which operates via Cloudflare Workers. On the remaining instances, instead of fonts.kavin.rocks, it gets the fonts from fonts.gstatic.com (Google).

I think that adding an easy way to serve fonts directly from the first-party or adding the ability to host a fonts.gstatic.com proxy (like fonts.kavin.rocks) would benefit user privacy. Not only would it benefit privacy, but it could also improve site security, as it allows for instances to restrict resources to the same origin (via CSP for example).

Related problems that may be fixed with the above: #997 #922 

### Why would this be useful to add?

Included above.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment] 2022-12-04 22:56
Duplicate of #658

**Comment by PrivacyDevel** [comment] 2022-12-10 01:52
I made a little [shell script](https://gist.github.com/PrivacyDevel/6cb4cff5353932b4c0a4a76e85bbbe23) that you can execute in your `dist` directory. It will download the required fonts and make sure that your instance is going to serve them from the local filesystem instead of pulling them from gstatic.com or kavin.rocks.

It's what I used on https://piped.privacydev.net.

**Comment by PrivacyDevel** [comment] 2022-12-10 02:24
This script could also be added to the repo and executed in the Dockerfile instead of the sed command if desired: https://github.com/TeamPiped/Piped/blob/a91531efa49209b18ea46b47bfa5b6951e350ab1/Dockerfile#L10
Should I create a PR for that?

**Comment by FireMasterK** [comment] 2022-12-10 04:24
> This script could also be added to the repo and called from the Dockerfile instead of the sed command if desired:
> 
> https://github.com/TeamPiped/Piped/blob/a91531efa49209b18ea46b47bfa5b6951e350ab1/Dockerfile#L10
> 
> 
> Should I create a PR for that?

Yes, that would be much appreciated!

**Closed** 2023-01-02 21:43 UTC
Labels: enhancement
