### ISSUE TITLE
Piped might be broken again

### ISSUE THREAD

**Issue by giselle-campos** [TeamPiped/Piped#2820] opened 2023-08-15 23:24 UTC
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

No videos play

### To Reproduce

- kalvin rocks is down
- tokhmi is down
- moomoo down
- syncpundit down
- mha.fi is working (thank god)

Mostly everything is down
even on mobile

### Expected behavior

works

### Browser, and OS with Version.

mobile android and browsers

### Additional context

Youtube keeps breaking the api

**Comment by janandreiiii** [comment] 2023-08-16 00:59
Yeah, I guess

**Comment by maxrave-dev** [comment] 2023-08-16 02:52
Request return 403 error
![image](https://github.com/TeamPiped/Piped/assets/113747128/cf2d4c64-5a59-4c24-b1bb-d12473968726)

**Comment by Inevitabilis** [comment] 2023-08-16 04:48
LibreTube (piped based android app) github has already answered this one, being less about breaking API and more about straight up banning piped proxy IPs
https://github.com/libre-tube/LibreTube/issues/4479#issuecomment-1678526890

**Comment by Bnyro** [comment] 2023-08-16 05:48
Duplicate of #2809

**Closed by Bnyro** 2023-08-16 05:48 UTC
Labels: bug
