### ISSUE TITLE
Low quality audio chosen even with high quality video

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [TeamPiped/Piped#1300] opened 2022-08-14 11:52 UTC
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Piped chooses ~50kbps Opus as the audio, even when the video is 1080p VP9.

### To Reproduce

1. Go to https://piped.kavin.rocks/ and set default quality to 1080p or higher
2. Load https://piped.kavin.rocks/watch?v=N72U-NFu44k with devtools open
3. See that it is loading video itag 248 (1080p VP9) and audio itag 249 (Opus 50kbps)

### Expected behavior

I expect high-quality audio to be chosen. YouTube chooses itag 251 (Opus 160kbps)

### Logs/Errors

GET request for video header (itag=248): `https://pipedproxy-ewr.kavin.rocks/videoplayback?expire=1660498164&ei=lNz4YrnsC4Po8wT75b2QDg&ip=45.61.174.115&id=o-AKzLGHYIhmn8eu0aHliwxnvoR7gVlQOP2abzLCNwlMa6&itag=248&source=youtube&requiressl=yes&mh=EW&mm=31%2C29&mn=sn-bpb5oxu-3c2d%2Csn-ab5sznzl&ms=au%2Crdu&mv=m&mvi=3&pl=24&gcr=us&initcwndbps=3157500&vprv=1&mime=video%2Fwebm&gir=yes&clen=3479749&dur=175.480&lmt=1587066821739742&mt=1660476291&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=2331224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALZGYQ6Kb3hjoLWT6BnV25YSTdqZobmagFTzh10eBazVAiAoNKWy7YdFssNBobgniSbVftbkqloPXP8KWQApikHqNA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgdrccfnd3BX_mgvsKnvgkva6XfdreEfXGlBW7eo0TTBgCIQDwrNK832s7LLSjvAaQyefIjmjY02BjWsOul3-8qXlYDg%3D%3D&cpn=xgYzdb4lVPGwgdZ9&host=rr3---sn-bpb5oxu-3c2d.googlevideo.com&range=0-200`

GET request for audio header (itag=249): `https://pipedproxy-ewr.kavin.rocks/videoplayback?expire=1660498164&ei=lNz4YrnsC4Po8wT75b2QDg&ip=45.61.174.115&id=o-AKzLGHYIhmn8eu0aHliwxnvoR7gVlQOP2abzLCNwlMa6&itag=249&source=youtube&requiressl=yes&mh=EW&mm=31%2C29&mn=sn-bpb5oxu-3c2d%2Csn-ab5sznzl&ms=au%2Crdu&mv=m&mvi=3&pl=24&gcr=us&initcwndbps=3157500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=997593&dur=175.521&lmt=1587066789727065&mt=1660476291&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=2331224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMrWK4YdJVGe1XI8CrhobiSYtFDTBcHtdcy00VZjw9_1AiEA--2-EANF64PHUuV-g9BjcK5gaU6rJ3R61vxb-9G_C1o%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgdrccfnd3BX_mgvsKnvgkva6XfdreEfXGlBW7eo0TTBgCIQDwrNK832s7LLSjvAaQyefIjmjY02BjWsOul3-8qXlYDg%3D%3D&cpn=xgYzdb4lVPGwgdZ9&host=rr3---sn-bpb5oxu-3c2d.googlevideo.com&range=0-258`

### Additional context

I'm pretty sure NewPipe chooses 160kbps Opus

**Comment by FireMasterK** [comment] 2022-08-14 18:37
This was caused by a typo on my end, fixed now!

**Closed** 2022-08-14 18:37 UTC
Labels: bug
