### ISSUE TITLE
more filters

### ISSUE THREAD

**Issue by imxade** [TeamPiped/Piped#1336] opened 2022-08-27 04:45 UTC
### Describe the feature

add more options to filter panel

### Why would this be useful to add?

to search in a better way

### Concept(s)

![filter](https://user-images.githubusercontent.com/56511165/187014740-04c4db5c-74ec-4386-96e6-e15b8ddfbcb4.png)

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment] 2022-08-27 07:51
Duplicate of #1336
Relevant NPE PR: https://github.com/TeamNewPipe/NewPipeExtractor/pull/904

**Closed by FireMasterK** 2022-08-27 07:51 UTC
Labels: enhancement
