### ISSUE TITLE
Got error: "Sign in to confirm that you're not a bot"

### ISSUE THREAD

**Issue by darkdevil090** [TeamPiped/Piped#3756] opened 2024-08-13 07:35 UTC
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

On almost all instances a i have tested in the public list i am seeing "Got error: "Sign in to confirm that you're not a bot"" instead of a video
![Opera Snapshot_2024-08-13_113526_piped video](https://github.com/user-attachments/assets/4fcbea39-0a45-46a1-be28-f18d1b4e841a)

Here is a link from a public instance with the same problem:
https://piped.kavin.rocks/watch?v=vJEbP2Vdq2U
/

### To Reproduce

https://piped.kavin.rocks/watch?v=vJEbP2Vdq2U

### Expected behavior

Video to play normally

### Logs/Errors

org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: "Sign in to confirm that you're not a bot" at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.checkPlayabilityStatus(YoutubeStreamExtractor.java:1016) at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:876) at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60) at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:77) at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72) at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:67) at me.kavin.piped.server.handlers.StreamHandlers.lambda$streamsResponse$0(StreamHandlers.java:54) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)

### Browser, and OS with Version.

Happens on multiple browsers and devices

**Comment by darkdevil090** [comment] 2024-08-13 07:36
please resolve this

**Comment by ifsdk** [comment] 2024-08-13 10:47
Also having this error and trying reload the page, i got stumbled among these upon a new one: "Watch on the latest version of YouTube."

**Comment by redoomed1** [comment] 2024-08-13 16:11
Duplicate of #3658

**Comment by s1nistr4** [comment] 2024-08-13 22:21
Google is mass banning piped instances, it's not really something piped can do other than obfuscating instances more.

**Closed** 2024-08-14 07:51 UTC
Labels: bug
