### ISSUE TITLE
[Feture Request] Hold logged users settings server side

### ISSUE THREAD

**Issue by Axeltherabbit** [TeamPiped/Piped#1097] opened 2022-05-28 12:54 UTC
I clear my cookies and cache when I close the browser so I have to change the my settings everytime I login.
I have to also change my settings everytime I login from a new device.
User settings are not privacy sensible so it should not be a issue

**Comment by EdwardLangdon** [comment] 2022-05-28 13:01
Rephrasing your comment would be great. It's hard to understand.

**Comment by FireMasterK** [comment] 2022-06-06 04:31
Duplicate of #496

**Closed by FireMasterK** 2022-06-06 04:31 UTC
