### ISSUE TITLE
Livestreams stop working after playing for a bit

### ISSUE THREAD

**Issue by hugoghx** [TeamPiped/Piped#3587] opened 2024-05-03 18:10 UTC
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

With the update of the player (https://github.com/TeamPiped/Piped/issues/2898), livestreams now play. 

Unfortunately another issue has now shown up. Once a livestream is loaded, if left playing for a while, it will eventually stop playing, show the thumbnail and the loading spinning wheel.

From a network calls perspective, when this happens, the player stops requesting the segments to play and only requests the `index.m3u8` files.

I tested this locally on my own instance and also in `piped.video`
(I used https://piped.video/watch?v=36YnV9STBqc)

### To Reproduce

1. Load any livestream
2. Leave it playing for a while (not sure how much time, but in my testing it doesn't take long)
3. Observe that it stops playing after a while

### Expected behavior

Livestream plays continuously until it ends or you close the page.

### Logs/Errors

This seems to be a frontend issue, I don't see any error logs.

### Browser, and OS with Version.

Brave 1.65.126 on Windows 11, Brave on iOS, Edge on Windows 11

**Comment by Bnyro** [comment] 2024-05-04 14:55
Duplicate of https://github.com/TeamPiped/Piped/issues/3065, also happens with normal videos.

**Closed by Bnyro** 2024-05-04 14:55 UTC
Labels: bug
