### ISSUE TITLE
Add Option to Import/Export Playlists

### ISSUE THREAD

**Issue by KrachBumms** [TeamPiped/Piped#1213] opened 2022-07-19 08:40 UTC
If I'm not mistaken, Piped is missing an option to import/export playlists.
Perhaps best would be an all in one import/export option that works for both subscriptions and playlists.

**Comment by FireMasterK** [comment] 2022-07-19 17:58
Duplicate of #1018

**Closed by FireMasterK** 2022-07-19 17:58 UTC
