### ISSUE TITLE
Cannot play a specific video

### ISSUE THREAD

**Issue by abacabadabacaba** [TeamPiped/Piped#2312] opened 2023-04-19 05:47 UTC
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

I cannot watch a specific video using piped.video. The same video plays fine on youtube.com.

### To Reproduce

Try to play [this video](https://piped.video/watch?v=H2bq4XLhMDc).

### Expected behavior

The video should load.

### Logs/Errors

The video loads endlessly.

### Browser, and OS with Version.

Browser: Brave 1.50.114 (Chromium 112.0.5615.49).
OS: ChromeOS 103.0.5060.132.

**Comment by kskarthik** [comment] 2023-04-21 12:26
the video plays fine for me (firefox 112) Linux

**Comment by FireMasterK** [comment] 2023-04-27 14:00
Closing this since I can't really reproduce this.

**Closed by FireMasterK** 2023-04-27 14:00 UTC
Labels: bug
