### ISSUE TITLE
 Some videos don't show up in feed from subscribed channels

### ISSUE THREAD

**Issue by helpthemfix** [TeamPiped/Piped#1457] opened 2022-09-19 23:20 UTC
### Official Instance

- [x] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

I noticed multiple channels don't show in my feed on the main instance. for example this video:
https://piped.kavin.rocks/watch?v=6E3ZS1b5SQA shows up in my feed on the mha.fi instance but not the main one.

### To Reproduce

1.  Subscibe to https://piped.kavin.rocks/channel/UCWPJwoVXJhv0-ucr3pUs1dA
 2. Go to feed
 3. New videos are not listed in the feed

### Expected behavior

New videos should be listed in the feed just as before. The problem is new.

### Logs/Errors

N/A

### Browser, and OS with Version.

Firefox 104
Windows 10

**Comment by Veloxization** [comment] 2022-09-20 05:02
Not a new issue. Seems to be a duplicate of #1130

**Closed** 2022-09-30 15:07 UTC
Labels: bug
