### ISSUE TITLE
All the tabs with Piped open refresh automatically

### ISSUE THREAD

**Issue by mojo-jojo-7** [TeamPiped/Piped#1906] opened 2022-12-21 14:26 UTC
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

All the tabs with Piped open refresh randomly by themselves. I tried to understand when this happens, but could not find any pattern. It even happens while watching a video.

### To Reproduce

Not sure how to reproduce this when wanted. I guess you just have to catch it when it happens

### Expected behavior

No automatic refreshes

### Logs/Errors

None

### Browser, and OS with Version.

Firefox 108.0.x on Windows 10

### Additional context

I'm using https://piped.kavin.rocks and it happens almost everyday. I did not observe this behavior on the official instance, but it's possible I did not use it enough to catch it happening. Perhaps it's some kind of push from the server due to an update?

**Comment by goodness-from-me** [comment] 2022-12-21 15:24
It usually happens whenever there is an update to frontend, eg new commit was pushed to master branch and CD published a new version.

**Comment by Bnyro** [comment] 2022-12-21 20:20
I somewhat doubt that's the reason, the frontend only consists of static files that are downloaded from the server once and then run on your browser. When there's an update/new commit to the frontend there's nothing that tells the browser to refresh the page as those files are only statically served.

**Comment by AlyoshaVasilieva** [comment] 2022-12-22 00:59
Enable "Store Watch History" to resume your progress in the video after the forced refresh after an update.

>When there's an update/new commit to the frontend there's nothing that tells the browser to refresh the page as those files are only statically served.

If you go to an instance after a few days of not using it, it doesn't load then refresh the page after a few seconds for you? This is reproducible for me on every instance. Also, if I manually update my private instance (build, pull, down, up), including frontend, and I visit it it will always force a refresh for me.

**Comment by Bnyro** [comment] 2023-01-26 20:58
Duplicate of #1199 apparently

**Closed by Bnyro** 2023-01-26 20:58 UTC
Labels: bug
