### ISSUE TITLE
Create sections/categories for your subscribed channels

### ISSUE THREAD

**Issue by abdo2048** [TeamPiped/Piped#1931] opened 2023-01-02 00:20 UTC
### Describe the feature

FreeTube has a feature that allows you to have multiple profiles, and in each profile it has it's own channels/subscriptions.
It's really handy if you want to organize your subscriptions. So I think if there is a sections or categories to organize your channels would be better.

### Why would this be useful to add?

For example, I would create a section (or whatever the name) where I move tech channel into it, and another section where I move Graphic Design into it, and so on.
The purpose is to organize your channels and reach it more fast.
So this creates sections or categories by topic, someone else could create sections according to another filter, and so on.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-01-27 18:07
Duplicate of #490

**Closed by Bnyro** 2023-01-27 18:07 UTC
Labels: enhancement
